### ISSUE TITLE
Flaky test: CheckStdoutWithLargeWrites - StdOut Logging

### ISSUE THREAD

**Issue by pakrym** [aspnet/IISIntegration#1048]
```
Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupExceptionTests.CheckStdoutWithLargeWrites(path: "CheckOversizedStdOutWrites") [FAIL]
  Failed   Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupExceptionTests.CheckStdoutWithLargeWrites(path: "CheckOversizedStdOutWrites")
RUNDOTNET : error Message:  [C:\Users\appveyor\.dotnet\buildtools\korebuild\2.2.0-preview1-17090\KoreBuild.proj]
   Assert.Contains() Failure
  Not found: (filter expression)
  In value:  ConcurrentQueue<WriteContext> [WriteContext { EventId = 0, Exception = null, Formatter = Func`3 { ... }, LoggerName = "Microsoft.AspNetCore.Server.IntegrationTesting.IIS"..., LogLevel = Information, ... }, WriteContext { EventId = 0, Exception = null, Formatter = Func`3 { ... }, LoggerName = "Microsoft.AspNetCore.Server.IntegrationTesting.IIS"..., LogLevel = Information, ... }, WriteContext { EventId = 0, Exception = null, Formatter = Func`3 { ... }, LoggerName = "Microsoft.AspNetCore.Server.IntegrationTesting.IIS"..., LogLevel = Information, ... }, WriteContext { EventId = 0, Exception = null, Formatter = Func`3 { ... }, LoggerName = "Microsoft.AspNetCore.Server.IntegrationTesting.IIS"..., LogLevel = Information, ... }, WriteContext { EventId = 0, Exception = null, Formatter = Func`3 { ... }, LoggerName = "Microsoft.AspNetCore.Server.IntegrationTesting.IIS"..., LogLevel = Information, ... }, ...]
  Stack Trace:
     at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupExceptionTests.CheckStdoutWithLargeWrites(String path) in /_/test/IISIntegration.FunctionalTests/Inprocess/StartupExceptionTests.cs:line 55
  --- End of st
```

**Comment by jkotalik** [comment]
```
2018-07-30T20:09:50.3530541Z   
2018-07-30T20:09:50.4193967Z   Starting test execution, please wait...
2018-07-30T20:09:52.5110778Z   [xUnit.net 00:00:00.51]     Microsoft.AspNetCore.Server.IIS.FunctionalTests.Inprocess.AppOfflineTests.AppOfflineDroppedWhileSiteStarting_SiteShutsDown_InProcess [SKIP]
2018-07-30T20:09:54.7994548Z   Skipped  Microsoft.AspNetCore.Server.IIS.FunctionalTests.Inprocess.AppOfflineTests.AppOfflineDroppedWhileSiteStarting_SiteShutsDown_InProcess
2018-07-30T20:10:28.1427909Z   [xUnit.net 00:00:35.14]     Microsoft.AspNetCore.Server.IIS.FunctionalTests.Inprocess.AppOfflineTests.AppOfflineDroppedWhileSiteFailedToStartInRequestHandler_SiteStops_InProcess [SKIP]
2018-07-30T20:10:28.1434034Z   [xUnit.net 00:00:35.14]     Microsoft.AspNetCore.Server.IIS.FunctionalTests.Inprocess.AppOfflineTests.AppOfflineDroppedWhileSiteRunning_SiteShutsDown_InProcess [SKIP]
2018-07-30T20:10:28.1434866Z   [xUnit.net 00:00:35.14]     Microsoft.AspNetCore.Server.IIS.FunctionalTests.Inprocess.AppOfflineTests.AppOfflineDroppedWhileSiteRunning_SiteShutsDown_OutOfProcess [SKIP]
2018-07-30T20:10:28.6446875Z   Skipped  Microsoft.AspNetCore.Server.IIS.FunctionalTests.Inprocess.AppOfflineTests.AppOfflineDroppedWhileSiteFailedToStartInRequestHandler_SiteStops_InProcess
2018-07-30T20:10:28.6453616Z   Skipped  Microsoft.AspNetCore.Server.IIS.FunctionalTests.Inprocess.AppOfflineTests.AppOfflineDroppedWhileSiteRunning_SiteShutsDown_InProcess
2018-07-30T20:10:28.6455365Z   Skipped  Microsoft.AspNetCore.Server.IIS.FunctionalTests.Inprocess.AppOfflineTests.AppOfflineDroppedWhileSiteRunning_SiteShutsDown_OutOfProcess
2018-07-30T20:11:40.1716353Z   [xUnit.net 00:01:46.07]     Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.HostingEnvironmentTests.HostingEnvironmentIsCorrect [SKIP]
2018-07-30T20:11:40.1718308Z   Skipped  Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.HostingEnvironmentTests.HostingEnvironmentIsCorrect
2018-07-30T20:12:08.0745420Z   [xUnit.net 00:02:14.06]     Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupExceptionTests.CheckStdoutWithLargeWrites(path: "CheckOversizedStdOutWrites") [FAIL]
2018-07-30T20:12:08.0749951Z   Failed   Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupExceptionTests.CheckStdoutWithLargeWrites(path: "CheckOversizedStdOutWrites")
2018-07-30T20:12:08.0751724Z   Error Message:
2018-07-30T20:12:08.0753005Z    Assert.Contains() Failure
2018-07-30T20:12:08.0754341Z   Not found: (filter expression)
2018-07-30T20:12:08.0757861Z   In value:  ConcurrentQueue<WriteContext> [WriteContext { EventId = 0, Exception = null, Formatter = Func`3 { ... }, LoggerName = "Microsoft.AspNetCore.Server.IntegrationTesting.IIS"..., LogLevel = Information, ... }, WriteContext { EventId = 0, Exception = null, Formatter = Func`3 { ... }, LoggerName = "Microsoft.AspNetCore.Server.IntegrationTesting.IIS"..., LogLevel = Information, ... }, WriteContext { EventId = 0, Exception = null, Formatter = Func`3 { ... }, LoggerName = "Microsoft.AspNetCore.Server.IntegrationTesting.IIS"..., LogLevel = Information, ... }, WriteContext { EventId = 0, Exception = null, Formatter = Func`3 { ... }, LoggerName = "Microsoft.AspNetCore.Server.IntegrationTesting.IIS"..., LogLevel = Information, ... }, WriteContext { EventId = 0, Exception = null, Formatter = Func`3 { ... }, LoggerName = "Microsoft.AspNetCore.Server.IntegrationTesting.IIS"..., LogLevel = Information, ... }, ...]
2018-07-30T20:12:08.0760771Z   Stack Trace:
2018-07-30T20:12:08.0762378Z      at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupExceptionTests.CheckStdoutWithLargeWrites(String path) in /_/test/Common.FunctionalTests/Inprocess/StartupExceptionTests.cs:line 59
2018-07-30T20:12:08.0763935Z   --- End of stack trace from previous location where exception was thrown ---
2018-07-30T20:12:08.0765240Z   Standard Output Messages:
2018-07-30T20:12:08.0767077Z    | [0.001s] TestLifetime Information: Starting test CheckStdoutWithLargeWrites-CheckOversizedStdOutWrites at 2018-07-30T20:12:01
2018-07-30T20:12:08.0767868Z    | [0.001s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Deploying [Variation] :: ServerType=IIS, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
2018-07-30T20:12:08.0782568Z    | [0.002s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
2018-07-30T20:12:08.0803717Z    | [0.002s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Executing command dotnet publish  --output "C:\Users\VssAdministrator\AppData\Local\Temp\9f58f705-a508-48d4-942e-e48588ff5e71" --framework netcoreapp2.2 --configuration Release --no-restore -p:VerifyMatchingImplicitPackageVersion=false 
2018-07-30T20:12:08.0804345Z    | [0.207s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
2018-07-30T20:12:08.0811287Z    | [0.207s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
2018-07-30T20:12:08.0811964Z    | [0.981s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout:   TestTasks -> D:\a\1\s\test\TestTasks\bin\Release\netcoreapp2.2\TestTasks.dll
2018-07-30T20:12:08.0812754Z    | [1.053s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout:   Microsoft.AspNetCore.Server.IIS -> D:\a\1\s\src\Microsoft.AspNetCore.Server.IIS\bin\Release\netstandard2.0\Microsoft.AspNetCore.Server.IIS.dll
2018-07-30T20:12:08.0813470Z    | [1.371s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout:   StartupExceptionWebSite -> D:\a\1\s\test\WebSites\StartupExceptionWebsite\bin\Release\netcoreapp2.2\StartupExceptionWebSite.dll
2018-07-30T20:12:08.0814273Z    | [1.861s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout:   StartupExceptionWebSite -> C:\Users\VssAdministrator\AppData\Local\Temp\9f58f705-a508-48d4-942e-e48588ff5e71\
2018-07-30T20:12:08.0814935Z    | [1.911s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet publish finished with exit code : 0
2018-07-30T20:12:08.0815634Z    | [1.913s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Backed up C:\Windows\system32\inetsrv\config\applicationhost.config to C:\Windows\system32\inetsrv\config\applicationhost.config.HttpTestSite20180730201201backup
2018-07-30T20:12:08.0816429Z    | [1.916s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Copied contents of IIS.config to C:\Windows\system32\inetsrv\config\applicationhost.config
2018-07-30T20:12:08.0817096Z    | [1.924s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Configured AppPool HttpTestSite20180730201201Pool
2018-07-30T20:12:08.0817815Z    | [1.924s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Configured Site HttpTestSite20180730201201 with AppPool HttpTestSite20180730201201Pool
2018-07-30T20:12:08.0818445Z    | [1.924s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Could not find AspNetCoreModuleV2 section in global modules; creating section.
2018-07-30T20:12:08.0819669Z    | [1.925s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Could not find AspNetCoreModuleV2 section in modules; creating section.
2018-07-30T20:12:08.0820098Z    | [2.689s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Site HttpTestSite20180730201201 has started.
2018-07-30T20:12:08.0820560Z    | [2.690s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Successfully finished IIS application directory setup.
2018-07-30T20:12:08.0821125Z    | [2.691s] HttpTestSite Debug: Method: GET, RequestUri: 'http://localhost:2152/CheckOversizedStdOutWrites', Version: 2.0, Content: <null>, Headers:
2018-07-30T20:12:08.0821422Z    |                              {
2018-07-30T20:12:08.0821687Z    |                              }
2018-07-30T20:12:08.0822050Z    | [2.864s] HttpTestSite Warning: StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
2018-07-30T20:12:08.0822402Z    |                                {
2018-07-30T20:12:08.0822713Z    |                                  Server: Microsoft-IIS/10.0
2018-07-30T20:12:08.0823049Z    |                                  Date: Mon, 30 Jul 2018 20:12:04 GMT
2018-07-30T20:12:08.0823316Z    |                                  Content-Type: text/html
2018-07-30T20:12:08.0823628Z    |                                  Content-Length: 1542
2018-07-30T20:12:08.0823883Z    |                                }
2018-07-30T20:12:08.0825253Z    | [2.864s] HttpTestSite Warning: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">             <html xmlns="http://www.w3.org/1999/xhtml">             <head>             <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />             <title> IIS 500.30 Error </title><style type="text/css"></style></head>             <body> <div id = "content">               <div class = "content-container"><h3> HTTP Error 500.30 - ANCM In-Process Start Failure </h3></div>                <div class = "content-container">                <fieldset> <h4> Common causes of this issue: </h4>                 <ul><li> The application failed to start </li>                  <li> The application started but then stopped </li>                  <li> The application started but threw an exception during startup </li></ul></fieldset>               </div>               <div class = "content-container">                 <fieldset><h4> Troubleshooting steps: </h4>                  <ul><li> Check the system event log for error messages </li>                  <li> Enable logging the application process' stdout messages </li>                  <li> Attach a debugger to the application process and inspect </li></ul></fieldset>                  <fieldset><h4> For more information visit:                  <a href="https://go.microsoft.com/fwlink/?LinkID=808681"> <cite> https://go.microsoft.com/fwlink/?LinkID=808681 </cite></a></h4>                  </fieldset>               </div>            </div></body></html>
2018-07-30T20:12:08.0826752Z    | [2.866s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Restored C:\Windows\system32\inetsrv\config\applicationhost.config.
2018-07-30T20:12:08.0827118Z    | [2.874s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Host process shutting down.
2018-07-30T20:12:08.0827908Z    | [2.874s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Warning: Could not read log file
2018-07-30T20:12:08.0828374Z    | [3.075s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Warning: Could not read log file
2018-07-30T20:12:08.0828766Z    | [3.276s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Warning: Could not read log file
2018-07-30T20:12:08.0829279Z    | [3.477s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Warning: Could not read log file
2018-07-30T20:12:08.0847898Z    | [3.677s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Warning: Could not read log file
2018-07-30T20:12:08.0848504Z    | [3.878s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Found debug log file: HttpTestSite20180730201201.txt
2018-07-30T20:12:08.0851787Z    | [4.048s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [Time]: Total time taken for this test variation '4.0463497' seconds
2018-07-30T20:12:08.0852290Z   
2018-07-30T20:12:08.0852642Z   
2018-07-30T20:12:15.6302100Z   Results File: D:\a\1\s\artifacts\logs\IIS.FunctionalTests-netcoreapp2.2-20180730.13.trx
2018-07-30T20:12:15.6303619Z   
```

**Comment by mikeharder** [comment]
@jkotalik : Is this related to https://github.com/aspnet/IISIntegration/issues/1100?

**Comment by jkotalik** [comment]
Yeah same issue it looks like.

**Comment by pakrym** [comment]
Fixed in https://github.com/aspnet/IISIntegration/pull/1242
