### ISSUE TITLE
Flaky test: CheckStdoutLoggingToPipe_DoesNotCrashProcess - ServerManager retries

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/IISIntegration#1089]
This test [fails](http://aspnetci/viewLog.html?buildId=513808&buildTypeId=XPlat_Windows_Win2008r2_Universe) occasionally with the following error:
```
System.DllNotFoundException : Unable to load DLL 'api-ms-win-service-core-l1-1-1.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.EnumServicesStatusEx(IntPtr databaseHandle, Int32 infolevel, Int32 serviceType, Int32 serviceState, IntPtr status, Int32 size, Int32& bytesNeeded, Int32& servicesReturned, Int32& resumeHandle, String group)
   at System.ServiceProcess.ServiceController.GenerateNames()
   at System.ServiceProcess.ServiceController.GetServiceHandle(Int32 desiredAccess)
   at System.ServiceProcess.ServiceController.GenerateStatus()
   at Microsoft.Web.Administration.ServerManager.GetServiceStatus(String serviceName)
   at Microsoft.Web.Administration.Site.get_State()
   at Microsoft.AspNetCore.Server.IntegrationTesting.IISApplication.WaitUntilSiteStarted() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISApplication.cs:line 101
   at Microsoft.AspNetCore.Server.IntegrationTesting.IISApplication.StartIIS(Uri uri, String contentRoot) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISApplication.cs:line 79
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.DeployAsync() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 70
   at Microsoft.AspNetCore.Server.IntegrationTesting.FunctionalTestsBase.DeployAsync(DeploymentParameters parameters) in /_/test/Common.FunctionalTests/Utilities/FunctionalTestsBase.cs:line 35
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.LoggingTests.CheckStdoutLoggingToPipe_DoesNotCrashProcess(String path) in /_/test/Common.FunctionalTests/Inprocess/LoggingTests.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.003s] TestLifetime Information: Starting test CheckStdoutLoggingToPipe_DoesNotCrashProcess-CheckErrLogFile at 2018-07-24T21:12:17
| [0.004s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Deploying [Variation] :: ServerType=IIS, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.004s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| [0.004s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Executing command dotnet publish  --output "C:\BuildAgent\temp\buildTmp\27db190a-2f59-4e08-88bc-58726a392499" --framework netcoreapp2.2 --configuration Release --no-restore -p:VerifyMatchingImplicitPackageVersion=false 
| [0.211s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
| [0.211s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| [1.175s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout:   TestTasks -> C:\BuildAgent\work\33bdfc1cae7b2a38\modules\IISIntegration\test\TestTasks\bin\Release\netcoreapp2.2\TestTasks.dll
| [1.255s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout:   Microsoft.AspNetCore.Server.IIS -> C:\BuildAgent\work\33bdfc1cae7b2a38\modules\IISIntegration\src\Microsoft.AspNetCore.Server.IIS\bin\Release\netstandard2.0\Microsoft.AspNetCore.Server.IIS.dll
| [1.599s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout:   InProcessWebSite -> C:\BuildAgent\work\33bdfc1cae7b2a38\modules\IISIntegration\test\WebSites\InProcessWebSite\bin\Release\netcoreapp2.2\InProcessWebSite.dll
| [2.385s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout:   InProcessWebSite -> C:\BuildAgent\temp\buildTmp\27db190a-2f59-4e08-88bc-58726a392499\
| [2.429s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet publish finished with exit code : 0
| [2.430s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Backed up C:\Windows\system32\inetsrv\config\applicationhost.config to C:\Windows\system32\inetsrv\config\applicationhost.config.HttpTestSite20180724141217backup
| [2.432s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Copied contents of IIS.config to C:\Windows\system32\inetsrv\config\applicationhost.config
| [2.445s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Could not add environment variables to worker process: Filename: 
|                                                                                      Error: Unrecognized element 'environmentVariables'
| [2.445s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Configured AppPool HttpTestSite20180724141217Pool
| [2.446s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Configured Site HttpTestSite20180724141217 with AppPool HttpTestSite20180724141217Pool
| [2.446s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Could not find AspNetCoreModuleV2 section in global modules; creating section.
| [2.446s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Could not find AspNetCoreModuleV2 section in modules; creating section.
| [2.637s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Restored C:\Windows\system32\inetsrv\config\applicationhost.config.
| [2.648s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Host process shutting down.
| [2.648s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Warning: Could not read log file
| [2.846s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Warning: Could not read log file
| [3.045s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer
...
```

**Comment by ryanbrandenburg** [comment]
CheckStdoutLoggingToPipe_DoesNotCrashProcess [failed again](http://aspnetci/viewLog.html?buildId=513800&buildTypeId=XPlat_Windows_Win7_Universe).

**Comment by ryanbrandenburg** [comment]
CheckStdoutLoggingToPipeWithFirstWrite [failed again](http://aspnetci/viewLog.html?buildId=514319&buildTypeId=XPlat_Windows_Win2008r2_Universe).

**Comment by ryanbrandenburg** [comment]
InvalidFilePathForLogs_ServerStillRuns [failed again](http://aspnetci/viewLog.html?buildId=514782&buildTypeId=XPlat_Windows_Win2008r2_Universe).

**Comment by jkotalik** [comment]
See https://github.com/aspnet/IISIntegration/pull/1096

**Comment by ryanbrandenburg** [comment]
CheckStdoutLoggingToPipe_DoesNotCrashProcess [failed with about the same error](http://aspnetci/viewLog.html?buildId=526890&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by mikeharder** [comment]
Fix is to add retries when calling `Site.get_State()`.  Related to https://github.com/aspnet/IISIntegration/issues/1156.

```
System.DllNotFoundException : Unable to load DLL 'api-ms-win-service-core-l1-1-1.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.EnumServicesStatusEx(IntPtr databaseHandle, Int32 infolevel, Int32 serviceType, Int32 serviceState, IntPtr status, Int32 size, Int32& bytesNeeded, Int32& servicesReturned, Int32& resumeHandle, String group)
   at System.ServiceProcess.ServiceController.GenerateNames()
   at System.ServiceProcess.ServiceController.GetServiceHandle(Int32 desiredAccess)
   at System.ServiceProcess.ServiceController.GenerateStatus()
   at Microsoft.Web.Administration.ServerManager.GetServiceStatus(String serviceName)
   at Microsoft.Web.Administration.Site.get_State()
   at Microsoft.AspNetCore.Server.IntegrationTesting.IISApplication.WaitUntilSiteStarted() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISApplication.cs:line 101
```

**Comment by ryanbrandenburg** [comment]
CheckStdoutLoggingToPipe_DoesNotCrashProcess [failed with about the same error](http://aspnetci/viewLog.html?buildId=527343&buildTypeId=XPlat_Windows_Win7_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by pakrym** [comment]
I hope that `api-ms-win-service-core` related issues would get fixed by https://github.com/aspnet/IISIntegration/pull/1197.

**Comment by pakrym** [comment]
Closing this to clean up the issue list .
