### ISSUE TITLE
Flaky test: TestValidWriteOperationsPost

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/IISIntegration#1092]
This test [fails](http://aspnetci/viewLog.html?buildId=514311&buildTypeId=XPlat_Windows_Win7_Universe) occasionally with the following error:
```
System.AggregateException : One or more errors occurred. (One or more errors occurred. (Unable to load DLL 'api-ms-win-service-core-l1-1-1.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E))) (The following constructor parameters did not have matching fixture data: IISTestSiteFixture fixture)
---- System.AggregateException : One or more errors occurred. (Unable to load DLL 'api-ms-win-service-core-l1-1-1.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E))
-------- System.DllNotFoundException : Unable to load DLL 'api-ms-win-service-core-l1-1-1.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
---- The following constructor parameters did not have matching fixture data: IISTestSiteFixture fixture
----- Inner Stack Trace #1 (System.AggregateException) -----
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.IISTestSiteFixture..ctor() in /_/test/Common.FunctionalTests/Utilities/IISTestSiteFixture.cs:line 37
----- Inner Stack Trace -----
   at Interop.mincore.EnumServicesStatusEx(IntPtr databaseHandle, Int32 infolevel, Int32 serviceType, Int32 serviceState, IntPtr status, Int32 size, Int32& bytesNeeded, Int32& servicesReturned, Int32& resumeHandle, String group)
   at System.ServiceProcess.ServiceController.GenerateNames()
   at System.ServiceProcess.ServiceController.GetServiceHandle(Int32 desiredAccess)
   at System.ServiceProcess.ServiceController.GenerateStatus()
   at Microsoft.Web.Administration.ServerManager.GetServiceStatus(String serviceName)
   at Microsoft.Web.Administration.Site.get_State()
   at Microsoft.AspNetCore.Server.IntegrationTesting.IISApplication.WaitUntilSiteStarted(ApplicationPool appPool) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISApplication.cs:line 90
   at Microsoft.AspNetCore.Server.IntegrationTesting.IISApplication.StartIIS(Uri uri, String contentRoot) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISApplication.cs:line 76
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.DeployAsync() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 83
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

**Comment by jkotalik** [comment]
@pakrym the "api-ms-win*" issue still seems to be happening. For now, it may be best to add a skip condition for IIS on win7?

**Comment by pakrym** [comment]
Sure

**Comment by jkotalik** [comment]
Closing in favor of https://github.com/aspnet/IISIntegration/issues/1069
