### ISSUE TITLE
Flaky test: ServerShutsDownWhenMainExits

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/IISIntegration#1127]
This test [fails](http://aspnetci/viewLog.html?buildId=518759&buildTypeId=Lite_UniverseTest) occasionally with the following error:
```
System.Net.Http.HttpRequestException : No connection could be made because the target machine actively refused it.
---- System.Net.Sockets.SocketException : No connection could be made because the target machine actively refused it.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.LoggingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/LoggingHandler.cs:line 25
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.RetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/RetryHandler.cs:line 36
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.ShutdownTests.ServerShutsDownWhenMainExits() in /_/test/IISExpress.FunctionalTests/InProcess/ShutdownTests.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test ServerShutsDownWhenMainExits at 2018-07-30T19:27:09
| [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Executing command dotnet publish  --output "C:\b\t\buildTmp\f40ad952-d4d4-4898-89a0-42f3bc88a1b6" --framework netcoreapp2.2 --configuration Release --no-restore -p:VerifyMatchingImplicitPackageVersion=false 
| [0.251s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
| [0.252s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| [1.396s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout:   TestTasks -> C:\b\w\33bdfc1cae7b2a38\modules\IISIntegration\test\TestTasks\bin\Release\netcoreapp2.2\TestTasks.dll
| [1.990s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout:   Microsoft.AspNetCore.Server.IIS -> C:\b\w\33bdfc1cae7b2a38\modules\IISIntegration\src\Microsoft.AspNetCore.Server.IIS\bin\Release\netstandard2.0\Microsoft.AspNetCore.Server.IIS.dll
| [1.990s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout:   InProcessWebSite -> C:\b\w\33bdfc1cae7b2a38\modules\IISIntegration\test\WebSites\InProcessWebSite\bin\Release\netcoreapp2.2\InProcessWebSite.dll
| [3.220s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout:   InProcessWebSite -> C:\b\t\buildTmp\f40ad952-d4d4-4898-89a0-42f3bc88a1b6\
| [3.273s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet publish finished with exit code : 0
| [3.273s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Attempting to start IIS Express on port: 61940
| [3.273s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Writing '[ANCMPath]' 'C:\b\t\buildTmp\f40ad952-d4d4-4898-89a0-42f3bc88a1b6\x64\aspnetcore.dll' to config
| [3.273s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Writing '[ANCMV2Path]' 'C:\b\t\buildTmp\f40ad952-d4d4-4898-89a0-42f3bc88a1b6\x64\aspnetcorev2.dll' to config
| [3.274s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Writing [PORT] '61940' to config
| [3.274s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Writing [ApplicationPhysicalPath] 'C:\b\t\buildTmp\f40ad952-d4d4-4898-89a0-42f3bc88a1b6' to config
| [3.279s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Saving Config to C:\b\t\buildTmp\tmpF84F.tmp
| [3.280s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Executing command : C:\Program Files\IIS Express\iisexpress.exe /site:HttpTestSite /config:C:\b\t\buildTmp\tmpF84F.tmp /trace:error /systray:false
| [3.280s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| [3.280s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [3.280s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: SET ASPNETCORE_MODULE_DEBUG=4
| [3.283s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Info
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by Eilon** [comment]
@jkotalik - can you take a look? Is this a flaky test? Flaky network? Can the test be modified to avoid network?

**Comment by pakrym** [comment]
I think this is fixed, it just didn't propagate through entire build.

**Comment by Eilon** [comment]
@pakrym do you know what change might have fixed it?

**Comment by pakrym** [comment]
https://github.com/aspnet/IISIntegration/pull/1120
