### ISSUE TITLE
Test failure: Gets500_30_ErrorPage

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/IISIntegration#1160]
This test [fails](http://aspnetci/viewLog.html?buildId=523669&buildTypeId=XPlat_Windows_Win10Universe) occasionally with the following error:
```
System.AggregateException : One or more errors occurred. (IIS failed to start site.) (The object identifier does not represent a valid object. (Exception from HRESULT: 0x800710D8))
---- System.TimeoutException : IIS failed to start site.
---- System.Runtime.InteropServices.COMException : The object identifier does not represent a valid object. (Exception from HRESULT: 0x800710D8)
----- Inner Stack Trace #1 (System.TimeoutException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IISApplication.WaitUntilSiteStarted() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISApplication.cs:line 122
   at Microsoft.AspNetCore.Server.IntegrationTesting.IISApplication.StartIIS(Uri uri, String contentRoot) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISApplication.cs:line 79
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.DeployAsync() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 85
   at Microsoft.AspNetCore.Server.IntegrationTesting.FunctionalTestsBase.DeployAsync(IISDeploymentParameters parameters) in /_/test/Common.FunctionalTests/Utilities/FunctionalTestsBase.cs:line 42
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupExceptionTests.Gets500_30_ErrorPage() in /_/test/Common.FunctionalTests/Inprocess/StartupExceptionTests.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace #2 (System.Runtime.InteropServices.COMException) -----
   at Microsoft.Web.Administration.Interop.IAppHostMethodInstance.Execute()
   at Microsoft.Web.Administration.ApplicationPool.Stop()
   at Microsoft.AspNetCore.Server.IntegrationTesting.IISApplication.StopAppPool() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISApplication.cs:line 307
   at Microsoft.AspNetCore.Server.IntegrationTesting.IISApplication.StopAndDeleteAppPool() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISApplication.cs:line 139
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.Dispose() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 36
   at Microsoft.AspNetCore.Server.IntegrationTesting.FunctionalTestsBase.StopServer() in /_/test/Common.FunctionalTests/Utilities/FunctionalTestsBase.cs:line 53
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 76
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test Gets500_30_ErrorPage at 2018-08-04T01:28:52
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Deploying [Variation] :: ServerType=IIS, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.009s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\4e84e135b05a4fef8dc7b10a88b99fcf\runtimes\unix\lib\netcoreapp2.0
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.019s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\4e84e135b05a4fef8dc7b10a88b99fcf\runtimes\unix\lib
| [0.019s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\4e84e135b05a4fef8dc7b10a88b99fcf\runtimes\unix
| [0.021s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\4e84e135b05a4fef8dc7b10a88b99fcf\runtimes\win\lib\netcoreapp2.0
| [0.021s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.023s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\4e84e135b05a4fef8dc7b10a88b99fcf\runtimes\win\lib
| [0.023s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\4e84e135b05a4fef8dc7b10a88b99fcf\runtimes\win
| [0.024s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\4e84e135b05a4fef8dc7b10a88b99fcf\runtimes
| [0.024s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\4e84e135b05a4fef8dc7b10a88b99fcf\x64
| [0.025s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying aspnetcorev2_inprocess.dll
| [0.026s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying aspnetcorev2_inprocess.pdb
| [0.034s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\4e84e135b05a4fef8dc7b10a88b99fcf
| [0.034s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying aspnetcorev2_inprocess.dll
| [0.036s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying aspnetcorev2_inprocess.pdb
| [0.047s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Abstractions.dll
| [0.049s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Core.dll
| [0.051s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Abstractions.dll
| [0.053s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.dll
| [0.055s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
| [0.057s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.Abstract
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CheckStdoutWithLargeWrites [failed with about the same error](http://aspnetci/viewLog.html?buildId=523669&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDroppedWhileSiteIsDown_SiteReturns503 [failed with about the same error](http://aspnetci/viewLog.html?buildId=524443&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDroppedWhileSiteIsDown_SiteReturns503 [failed with about the same error](http://aspnetci/viewLog.html?buildId=525059&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Gets500_30_ErrorPage [failed with about the same error](http://aspnetci/viewLog.html?buildId=526879&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.
