### ISSUE TITLE
Test failure: GetServerVariableDoesNotCrash

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/IISIntegration#1163]
This test [fails](http://aspnetci/viewLog.html?buildId=524443&buildTypeId=XPlat_Windows_Win10Universe) occasionally with the following error:
```
System.AggregateException : One or more errors occurred. (One or more errors occurred. (IIS failed to start site.)) (The following constructor parameters did not have matching fixture data: IISTestSiteFixture fixture)
---- System.AggregateException : One or more errors occurred. (IIS failed to start site.)
-------- System.TimeoutException : IIS failed to start site.
---- The following constructor parameters did not have matching fixture data: IISTestSiteFixture fixture
----- Inner Stack Trace #1 (System.AggregateException) -----
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.IISTestSiteFixture..ctor() in /_/test/Common.FunctionalTests/Utilities/IISTestSiteFixture.cs:line 37
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IISApplication.WaitUntilSiteStarted() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISApplication.cs:line 126
   at Microsoft.AspNetCore.Server.IntegrationTesting.IISApplication.StartIIS(Uri uri, String contentRoot) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISApplication.cs:line 80
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.DeployAsync() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 85
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @Eilon,@muratg,@mkArtakMSFT

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
ReadAndWriteCopyToAsync [failed with about the same error](http://aspnetci/viewLog.html?buildId=525059&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
TestReadOffsetWorks [failed with about the same error](http://aspnetci/viewLog.html?buildId=526877&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AddResponseHeaders_HeaderValuesAreSetCorrectly [failed with about the same error](http://aspnetci/viewLog.html?buildId=527354&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.
