### ISSUE TITLE
Test failure: AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/IISIntegration#1193]
This test [fails](http://aspnetci/viewLog.html?buildId=526800&buildTypeId=XPlat_Windows_Win10Universe) occasionally with the following error:
```
System.AggregateException : One or more errors occurred. (Filename: \\?\C:\WINDOWS\system32\inetsrv\config\redirection.config
Line number: 14
Error: Can not log on locally to C:\BuildAgent\temp\buildTmp\e0165681-62e9-4e6e-b017-9690a1dca0cb as user MyUser with redirection.config password
) (Filename: \\?\C:\WINDOWS\system32\inetsrv\config\redirection.config
Line number: 14
Error: Can not log on locally to C:\BuildAgent\temp\buildTmp\e0165681-62e9-4e6e-b017-9690a1dca0cb as user MyUser with redirection.config password
)
---- System.Runtime.InteropServices.COMException : Filename: \\?\C:\WINDOWS\system32\inetsrv\config\redirection.config
Line number: 14
Error: Can not log on locally to C:\BuildAgent\temp\buildTmp\e0165681-62e9-4e6e-b017-9690a1dca0cb as user MyUser with redirection.config password
---- System.Runtime.InteropServices.COMException : Filename: \\?\C:\WINDOWS\system32\inetsrv\config\redirection.config
Line number: 14
Error: Can not log on locally to C:\BuildAgent\temp\buildTmp\e0165681-62e9-4e6e-b017-9690a1dca0cb as user MyUser with redirection.config password
----- Inner Stack Trace #1 (System.Runtime.InteropServices.COMException) -----
   at Microsoft.Web.Administration.Interop.IAppHostAdminManager.GetAdminSection(String bstrSectionName, String bstrPath)
   at Microsoft.Web.Administration.Configuration.GetSectionInternal(ConfigurationSection section, String sectionPath, String locationPath)
   at Microsoft.Web.Administration.Lazy.Initialize[T](T& target, CreateInstanceDelegate`1 valueFactory)
   at Microsoft.Web.Administration.ServerManager.SitesCollectionCreator()
   at Microsoft.Web.Administration.Lazy.Initialize[T](T& target, CreateInstanceDelegate`1 valueFactory)
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.WaitUntilSiteStarted() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 173
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.StartIIS(Uri uri, String contentRoot) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 161
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.DeployAsync() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 113
   at Microsoft.AspNetCore.Server.IntegrationTesting.FunctionalTestsBase.DeployAsync(IISDeploymentParameters parameters) in /_/test/Common.FunctionalTests/Utilities/FunctionalTestsBase.cs:line 46
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.AppOfflineTests.DeployApp(HostingModel hostingModel) in /_/test/Common.FunctionalTests/AppOfflineTests.cs:line 210
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.AppOfflineTests.AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks(HostingModel hostingModel) in /_/test/Common.FunctionalTests/AppOfflineTests.cs:line 158
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace #2 (System.Runtime.InteropServices.COMException) -----
   at Microsoft.Web.Administration.Interop.IAppHostAdminManager.GetAdminSection(String bstrSectionName, String bstrPath)
   at Microsoft.Web.Administration.Configuration.GetSectionInternal(ConfigurationSection section, String sectionPath, String locationPath)
   at Microsoft.Web.Administration.Lazy.Initialize[T](T& target, CreateInstanceDelegate`1 valueFactory)
   at Microsoft.Web.Administration.ServerManager.SitesCollectionCreator()
   at Microsoft.Web.Administration.Lazy.Initialize[T](T& target, CreateInstanceDelegate`1 valueFactory)
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.Stop() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 363
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.StopAndDeleteAppPool() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 222
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.Dispose() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 53
   at Microsoft.AspNetCore.Server.IntegrationTesting.FunctionalTestsBase.StopServer() in /_/test/Common.FunctionalTests/Utilities/FunctionalTestsBase.cs:line 57
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 76
------- Stdout: -------
| [0.016s] TestLifetime Information: Starting test AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks-InProcess at 2018-08-09T14:54:55
| [0.059s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Deploying [Variation] :: ServerType=IIS, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.072s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Executing command dotnet publish  --output "C:\BuildAgent\temp\buildTmp\2ef7ce61f57944dc86fc23d4dac7117c" --framework netcoreapp2.2 --configuration Release --no-restore -p:VerifyMatchingImplicitPackageVersion=false 
| [0.382s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
| [0.382s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| [1.563s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout:   TestTasks -> C:\BuildAgent\work\33bdfc1cae7b2a38\modules\IISIntegration\test\TestTasks\bin\Release\netcoreapp2.2\TestTasks.dll
| [1.689s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: dotnet-publish stdout:   Microsoft.AspNetCore.Server.IIS -> C:\BuildAgent\work\33bdfc1cae7b2a38\modules\IISIntegration\src\Microsoft.AspNetCore.Server.IIS\bin\Release\nets
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

CC @muratg

This issue was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks [failed with about the same error](http://aspnetci/viewLog.html?buildId=526615&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks [failed with about the same error](http://aspnetci/viewLog.html?buildId=526599&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks [failed with about the same error](http://aspnetci/viewLog.html?buildId=526488&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks [failed with about the same error](http://aspnetci/viewLog.html?buildId=526494&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks [failed with about the same error](http://aspnetci/viewLog.html?buildId=526477&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks [failed with about the same error](http://aspnetci/viewLog.html?buildId=526508&buildTypeId=Releases_22xPublic_Win2012).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CheckStdoutLoggingToFile [failed with about the same error](http://aspnetci/viewLog.html?buildId=526475&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks [failed with about the same error](http://aspnetci/viewLog.html?buildId=526453&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks [failed with about the same error](http://aspnetci/viewLog.html?buildId=526280&buildTypeId=XPlat_Windows_Win8_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks [failed with about the same error](http://aspnetci/viewLog.html?buildId=526263&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineAddedAndRemovedStress [failed with about the same error](http://aspnetci/viewLog.html?buildId=526261&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
AppOfflineDropped_CanRemoveAppOfflineAfterAddingAndSiteWorks [failed with about the same error](http://aspnetci/viewLog.html?buildId=526220&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by pakrym** [comment]
Fixed by fixing the agent.
