### ISSUE TITLE
Test failure: CheckStartupEventLogMessage

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/IISIntegration#1203]
This test [fails](http://aspnetci/viewLog.html?buildId=527354&buildTypeId=XPlat_Windows_Win2008r2_Universe) occasionally with the following error:
```
System.AggregateException : One or more errors occurred. (IIS failed to start site.) (Object reference not set to an instance of an object.)
---- System.TimeoutException : IIS failed to start site.
---- System.NullReferenceException : Object reference not set to an instance of an object.
----- Inner Stack Trace #1 (System.TimeoutException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.WaitUntilSiteStarted() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 214
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.StartIIS(Uri uri, String contentRoot) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 161
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.DeployAsync() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 113
   at Microsoft.AspNetCore.Server.IntegrationTesting.FunctionalTestsBase.DeployAsync(IISDeploymentParameters parameters) in /_/test/Common.FunctionalTests/Utilities/FunctionalTestsBase.cs:line 47
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.EventLogTests.CheckStartupEventLogMessage() in /_/test/Common.FunctionalTests/Inprocess/EventLogTests.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace #2 (System.NullReferenceException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.WaitUntilSiteStopped() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 245
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.StopAndDeleteAppPool() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 226
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.Dispose() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 53
   at Microsoft.AspNetCore.Server.IntegrationTesting.FunctionalTestsBase.StopServer() in /_/test/Common.FunctionalTests/Utilities/FunctionalTestsBase.cs:line 58
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 76
------- Stdout: -------
| [0.002s] TestLifetime Information: Starting test CheckStartupEventLogMessage at 2018-08-09T22:12:51
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Deploying [Variation] :: ServerType=IIS, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.009s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\787fdbebce744e30944f348cc771daa1\runtimes\unix\lib\netcoreapp2.0
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\787fdbebce744e30944f348cc771daa1\runtimes\unix\lib
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\787fdbebce744e30944f348cc771daa1\runtimes\unix
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\787fdbebce744e30944f348cc771daa1\runtimes\win\lib\netcoreapp2.0
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.014s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\787fdbebce744e30944f348cc771daa1\runtimes\win\lib
| [0.014s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\787fdbebce744e30944f348cc771daa1\runtimes\win
| [0.015s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\787fdbebce744e30944f348cc771daa1\runtimes
| [0.015s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\787fdbebce744e30944f348cc771daa1\wwwroot
| [0.015s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying static.txt
| [0.015s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\787fdbebce744e30944f348cc771daa1
| [0.016s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying aspnetcorev2_inprocess.dll
| [0.017s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying aspnetcorev2_inprocess.pdb
| [0.035s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.deps.json
| [0.035s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.dll
| [0.035s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.pdb
| [0.035s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying InProcessWebSite.runtimeconfig.json
| [0.036s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Abstractions.dll
| [0.038s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Core.dll
| [0.039s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Abstractions.dll
| [0.040s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.dll
| [0.042s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
| [0.044s] Microsoft.AspNe
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @muratg

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
FailsAndLogsEventLogForMixedHostingModel [failed with about the same error](http://aspnetci/viewLog.html?buildId=527554&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by ryanbrandenburg** [comment]
CheckStartupEventLogMessage [failed with about the same error](http://aspnetci/viewLog.html?buildId=527607&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by pakrym** [comment]
Closing. It's another of site startup exceptions that we seem to have gotten rid of.
