### ISSUE TITLE
Test failure: CheckStdoutWithLargeWrites

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/IISIntegration#1297]
This test [fails](http://aspnetci/viewLog.html?buildId=537224&buildTypeId=Releases_22xPublic_Win2012) occasionally with the following error:
```
System.AggregateException : One or more errors occurred. (dotnet publish exited with exit code : 1) (Object reference not set to an instance of an object.)
---- System.Exception : dotnet publish exited with exit code : 1
---- System.NullReferenceException : Object reference not set to an instance of an object.
----- Inner Stack Trace #1 (System.Exception) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationPublisher.Publish(DeploymentParameters deploymentParameters, ILogger logger)
   at Microsoft.AspNetCore.Server.IntegrationTesting.CachingApplicationPublisher.Publish(DeploymentParameters deploymentParameters, ILogger logger)
   at Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationDeployer.DotnetPublish(String publishRoot)
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer.DeployAsync() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISExpressDeployer.cs:line 60
   at Microsoft.AspNetCore.Server.IntegrationTesting.FunctionalTestsBase.DeployAsync(IISDeploymentParameters parameters) in /_/test/Common.FunctionalTests/Utilities/FunctionalTestsBase.cs:line 37
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupExceptionTests.CheckStdoutWithLargeWrites(String path) in /_/test/Common.FunctionalTests/Inprocess/StartupExceptionTests.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace #2 (System.NullReferenceException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationDeployer.CleanPublishedOutput()
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer.Dispose(Boolean gracefulShutdown) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISExpressDeployer.cs:line 419
   at Microsoft.AspNetCore.Server.IntegrationTesting.FunctionalTestsBase.Dispose() in /_/test/Common.FunctionalTests/Utilities/FunctionalTestsBase.cs:line 42
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 76
------- Stdout: -------
| [0.003s] TestLifetime Information: Starting test CheckStdoutWithLargeWrites-CheckOversizedStdOutWrites at 2018-08-23T00:24:37
| [0.004s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.004s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Executing command dotnet publish  --output "C:\b\t\buildTmp\d852b0e9f9ab4cfd9a90369542598500" --framework netcoreapp2.2 --configuration Release --no-restore -p:VerifyMatchingImplicitPackageVersion=false 
| [0.222s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
| [0.222s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| [1.615s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout:   TestTasks -> C:\b\w\33bdfc1cae7b2a38\modules\IISIntegration\test\TestTasks\bin\Release\netcoreapp2.2\TestTasks.dll
| [1.691s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout: C:\b\w\33bdfc1cae7b2a38\.packages\internal.aspnetcore.sdk\2.2.0-preview1-20180807.2\build\GenerateAssemblyInfo.targets(25,5): error MSB4062: The "Microsoft.AspNetCore.BuildTools.Sdk_GetAssemblyFileVersion" task could not be loaded from the assembly C:\b\w\33bdfc1cae7b2a38\.packages\internal.aspnetcore.sdk\2.2.0-preview1-20180807.2\build\..\tools\netcoreapp2.1\Internal.AspNetCore.Sdk.dll. Assembly with same name is already loaded Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [C:\b\w\33bdfc1cae7b2a38\modules\IISIntegration\src\Microsoft.AspNetCore.Server.IIS\Microsoft.AspNetCore.Server.IIS.csproj]
| [1.725s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Error: dotnet publish exited with exit code : 1
| [1.725s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Warning: Host process already exited or never started successfully.
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.2.

CC @muratg

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
CheckStdoutWithLargeWrites [failed with about the same error](http://aspnetci/viewLog.html?buildId=537224&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
CheckStdoutWithRandomNumber [failed with about the same error](http://aspnetci/viewLog.html?buildId=537725&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Gets500_30_ErrorPage [failed with about the same error](http://aspnetci/viewLog.html?buildId=539623&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
CheckStdoutWithLargeWrites [failed with about the same error](http://aspnetci/viewLog.html?buildId=539776&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.
