### ISSUE TITLE
Test failure: AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#1346]
```
  Failed   Microsoft.AspNetCore.Server.IIS.FunctionalTests.AppOfflineTests.AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed(hostingModel: OutOfProcess, statusCode: 502, content: "502.5")
  Error Message:
   System.AggregateException : Operation did not succeed after 9 retries (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet)
  ---- System.InvalidOperationException : WorkerProcess not stopped yet
  ---- System.InvalidOperationException : WorkerProcess not stopped yet
  ---- System.InvalidOperationException : WorkerProcess not stopped yet
  ---- System.InvalidOperationException : WorkerProcess not stopped yet
  ---- System.InvalidOperationException : WorkerProcess not stopped yet
  ---- System.InvalidOperationException : WorkerProcess not stopped yet
  ---- System.InvalidOperationException : WorkerProcess not stopped yet
  ---- System.InvalidOperationException : WorkerProcess not stopped yet
  ---- System.InvalidOperationException : WorkerProcess not stopped yet
  Stack Trace:
     at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 416
     at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.Stop() in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 323
     at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.Dispose(Boolean gracefulShutdown) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 55
     at Microsoft.AspNetCore.Server.IntegrationTesting.FunctionalTestsBase.Dispose() in /_/test/Common.FunctionalTests/Utilities/FunctionalTestsBase.cs:line 50
     at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 76
  ----- Inner Stack Trace #1 (System.InvalidOperationException) -----
     at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<Stop>b__21_0(ServerManager serverManager) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 362
     at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 397
  ----- Inner Stack Trace #2 (System.InvalidOperationException) -----
     at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<Stop>b__21_0(ServerManager serverManager) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 362
     at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 397
  ----- Inner Stack Trace #3 (System.InvalidOperationException) -----
     at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<Stop>b__21_0(ServerManager serverManager) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 362
     at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 397
  ----- Inner Stack Trace #4 (System.InvalidOperationException) -----
     at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<Stop>b__21_0(ServerManager serverManager) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 362
     at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/IISDeployer.cs:line 397
```

Work process isn't being stopped.

# Logs
https://ci.appveyor.com/project/aspnetci/iisintegration/build/1.0.2201

# Run single test
```
dotnet test --no-build --filter "DisplayName~AppOfflineDroppedWhileSiteFailedToStartInShim_AppOfflineServed&DisplayName~OutOfProcess"
```

**Comment by mikeharder** [comment]
@jkotalik: Should this be addressed by #1338?

**Comment by jkotalik** [comment]
No. This is an issue with the site not shutting down.

**Comment by mikeharder** [comment]
No repro on a single-core VM with 3 `dotnet.exe` processes using 100% CPU in the background.  Closing for now, will reactivate if it repros again.  The only possible fix I see is to increase the timeout for w3wp.exe shutdown.
