### ISSUE TITLE
Test failure: CheckInvalidHostingModelParameter

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/IISIntegration#1347]
This test [fails](http://aspnetci/viewLog.html?buildId=540937&buildTypeId=XPlat_Windows_Win8_Universe) occasionally with the following error:
```
'Unknown hosting model 'bogus'. Please specify either hostingModel="inprocess" or hostingModel="outofprocess" in the web.config file.' didn't match any event log messaged.
Expected: True
Actual:   False
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.EventLogHelpers.VerifyEventLogEvent(IISDeploymentResult deploymentResult, ITestSink testSink, String expectedRegexMatchString) in /_/test/Common.FunctionalTests/Utilities/EventLogHelpers.cs:line 75
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupTests.CheckInvalidHostingModelParameter() in /_/test/IISExpress.FunctionalTests/InProcess/StartupTests.cs:line 161
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test CheckInvalidHostingModelParameter at 2018-08-28T18:57:24
| [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\504c8282f02d4d1abb6b8bb6b063ad30\runtimes\unix\lib\netcoreapp2.0
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\504c8282f02d4d1abb6b8bb6b063ad30\runtimes\unix\lib
| [0.009s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\504c8282f02d4d1abb6b8bb6b063ad30\runtimes\unix
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\504c8282f02d4d1abb6b8bb6b063ad30\runtimes\win\lib\netcoreapp2.0
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [0.011s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\504c8282f02d4d1abb6b8bb6b063ad30\runtimes\win\lib
| [0.011s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\504c8282f02d4d1abb6b8bb6b063ad30\runtimes\win
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\504c8282f02d4d1abb6b8bb6b063ad30\runtimes
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\504c8282f02d4d1abb6b8bb6b063ad30\wwwroot
| [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying static.txt
| [0.013s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\504c8282f02d4d1abb6b8bb6b063ad30
| [0.013s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying aspnetcorev2_inprocess.dll
| [0.014s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying aspnetcorev2_inprocess.pdb
| [0.029s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.deps.json
| [0.030s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.dll
| [0.031s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.pdb
| [0.033s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.runtimeconfig.json
| [0.034s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Abstractions.dll
| [0.038s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Core.dll
| [0.039s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Abstractions.dll
| [0.041s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.dll
| [0.042s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
| [0.044s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Abstractions.dll
| [0.045s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.dll
| [0.053s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Extensions.dll
| [0.054s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Http.Features.dll
| [0.064s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.dll
| [0.065s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.pdb
| [0.066s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Server.IIS.xml
| [0.068s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.WebUtilities.dll
| [0.069s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.Extensions.Configuration.Abstractions.dll
| [0.071s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.Extensions.Configuration.Binder.dll
| [0.072s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Cop
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @muratg

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by jkotalik** [comment]
#1338 should fix this issue. Seems like an event log message wasn't caught.
