### ISSUE TITLE
Test failure: AppOfflineDroppedWhileSiteFailedToStartInRequestHandler_SiteStops_InProcess

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/IISIntegration#1389]
This test [fails](http://aspnetci/viewLog.html?buildId=551491&buildTypeId=XPlat_Windows_Win10Universe) occasionally with the following error:
```
Assert.Equal() Failure
Expected: 0
Actual:   255
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.Helpers.AssertWorkerProcessStop(IISDeploymentResult deploymentResult) in /_/test/Common.FunctionalTests/Utilities/Helpers.cs:line 123
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.Helpers.AssertRecycledAsync(IISDeploymentResult deploymentResult, Func`1 verificationAction) in /_/test/Common.FunctionalTests/Utilities/Helpers.cs:line 134
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.AppOfflineTests.AppOfflineDroppedWhileSiteFailedToStartInRequestHandler_SiteStops_InProcess() in /_/test/Common.FunctionalTests/AppOfflineTests.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test AppOfflineDroppedWhileSiteFailedToStartInRequestHandler_SiteStops_InProcess at 2018-09-11T19:30:44
| [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| [0.009s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Executing command dotnet publish  --output "C:\BuildAgent\temp\buildTmp\c20593cdc222419eb2eac35458b93b18" --framework netcoreapp2.2 --configuration Release --no-restore -p:VerifyMatchingImplicitPackageVersion=false 
| [0.338s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
| [0.339s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| [2.035s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout:   TestTasks -> C:\BuildAgent\work\33bdfc1cae7b2a38\modules\IISIntegration\test\TestTasks\bin\Release\netcoreapp2.2\TestTasks.dll
| [2.150s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout:   Microsoft.AspNetCore.Server.IIS -> C:\BuildAgent\work\33bdfc1cae7b2a38\modules\IISIntegration\src\Microsoft.AspNetCore.Server.IIS\bin\Release\netstandard2.0\Microsoft.AspNetCore.Server.IIS.dll
| [2.577s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout:   InProcessWebSite -> C:\BuildAgent\work\33bdfc1cae7b2a38\modules\IISIntegration\test\WebSites\InProcessWebSite\bin\Release\netcoreapp2.2\InProcessWebSite.dll
| [3.075s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet-publish stdout:   InProcessWebSite -> C:\BuildAgent\temp\buildTmp\c20593cdc222419eb2eac35458b93b18\
| [3.147s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: dotnet publish finished with exit code : 0
| [3.159s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\75701587d43e4e61b2cde8f0ddf704d0\runtimes\unix\lib\netcoreapp2.0
| [3.160s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [3.163s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\75701587d43e4e61b2cde8f0ddf704d0\runtimes\unix\lib
| [3.163s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\75701587d43e4e61b2cde8f0ddf704d0\runtimes\unix
| [3.165s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\75701587d43e4e61b2cde8f0ddf704d0\runtimes\win\lib\netcoreapp2.0
| [3.165s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying System.Security.Principal.Windows.dll
| [3.167s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\75701587d43e4e61b2cde8f0ddf704d0\runtimes\win\lib
| [3.167s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\75701587d43e4e61b2cde8f0ddf704d0\runtimes\win
| [3.167s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\75701587d43e4e61b2cde8f0ddf704d0\runtimes
| [3.168s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\75701587d43e4e61b2cde8f0ddf704d0\wwwroot
| [3.168s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying static.txt
| [3.169s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Processing C:\BuildAgent\temp\buildTmp\75701587d43e4e61b2cde8f0ddf704d0
| [3.169s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying aspnetcorev2_inprocess.dll
| [3.171s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying aspnetcorev2_inprocess.pdb
| [3.180s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.deps.json
| [3.181s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.dll
| [3.183s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.pdb
| [3.184s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying InProcessWebSite.runtimeconfig.json
| [3.186s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Abstractions.dll
| [3.187s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug:   Copying Microsoft.AspNetCore.Authenticatio
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @muratg

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
AppOfflineDroppedWhileSiteFailedToStartInRequestHandler_SiteStops_InProcess [failed with about the same error](http://aspnetci/viewLog.html?buildId=552263&buildTypeId=XPlat_Windows_Win10Universe) on master.

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by muratg** [comment]
@pakrym @jkotalik please take a look.

**Comment by pakrym** [comment]
It's disabled and merged to master

**Comment by pakrym** [comment]
https://github.com/aspnet/IISIntegration/pull/1396
