### ISSUE TITLE
Test failure: ClosesAfterDataSent

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/IISIntegration#1405]
This test [fails](http://aspnetci/viewLog.html?buildId=557106&buildTypeId=Releases_22xPublic_Win2012) occasionally with the following error:
```
Assert.Contains() Failure
Not found: Server: Microsoft-IIS/10.0
In value:  List<String> ["Transfer-Encoding: chunked", "Server: Microsoft-IIS/8.5", "Date: Wed, 19 Sep 2018 05:57:23 GMT", ""]
   at Microsoft.AspNetCore.Server.IntegrationTesting.TestConnection.ReceiveHeaders(String[] lines) in /_/test/Common.Tests/Utilities/TestConnections.cs:line 204
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.ResponseAbortTests.ClosesAfterDataSent() in /_/test/IIS.Tests/ResponseAbortTests.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.001s] TestLifetime Information: Starting test ClosesAfterDataSent at 2018-09-19T05:57:21
| [2.046s] Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.TestServer Debug: Method: GET, RequestUri: 'http://localhost:58636/start', Version: 2.0, Content: <null>, Headers:
|                                                                                       {
|                                                                                       }
| [2.051s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [2.052s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [2.052s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly IIS.Tests, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
| [2.053s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://localhost:58636/start  
| [2.053s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.4561ms 200 
| [2.054s] Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.TestServer Debug: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
|                                                                                       {
|                                                                                         Transfer-Encoding: chunked
|                                                                                         Server: Microsoft-IIS/8.5
|                                                                                         Date: Wed, 19 Sep 2018 05:57:23 GMT
|                                                                                       }
| [2.054s] Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.TestServer Debug: Done
| [2.056s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http://localhost/  1
| [2.072s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [302.073s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 300014.9796ms 200 
| [303.446s] TestLifetime Information: Finished test ClosesAfterDataSent in 303.442544s
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on 2.2.

CC @muratg

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
ClosesAfterDataSent [failed with about the same error](http://aspnetci/viewLog.html?buildId=557215&buildTypeId=Releases_22xPublic_Win2012) on 2.2.

This comment was made automatically. If there is a problem contact ryanbrandenburg.
