### ISSUE TITLE
Test failure: ReaderThrowsResetExceptionOnInvalidBody

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/IISIntegration#1426]
This test [fails](http://aspnetci/viewLog.html?buildId=558092&buildTypeId=XPlat_Windows_Win8_Universe) occasionally with the following error:
```
System.TimeoutException : The operation at /_/test/IIS.Tests/ClientDisconnectTests.cs:238 timed out after reaching the limit of 300000ms.
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.ClientDisconnectTests.ReaderThrowsResetExceptionOnInvalidBody() in /_/test/IIS.Tests/ClientDisconnectTests.cs:line 238
--- End of stack trace from previous location where exception was thrown ---
------- Stdout: -------
| [0.011s] TestLifetime Information: Starting test ReaderThrowsResetExceptionOnInvalidBody at 2018-09-21T02:07:33
| [7.645s] Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.TestServer Debug: Method: GET, RequestUri: 'http://localhost:61682/start', Version: 2.0, Content: <null>, Headers:
|                                                                                       {
|                                                                                       }
| [7.651s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
| [7.651s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
| [7.652s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly IIS.Tests, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
| [7.652s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 GET http://localhost:61682/start  
| [7.652s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 0.5482ms 200 
| [7.653s] Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.TestServer Debug: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
|                                                                                       {
|                                                                                         Transfer-Encoding: chunked
|                                                                                         Server: Microsoft-IIS/8.5
|                                                                                         Date: Fri, 21 Sep 2018 02:07:40 GMT
|                                                                                       }
| [7.653s] Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.TestServer Debug: Done
| [307.667s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [309.674s] TestLifetime Information: Finished test ReaderThrowsResetExceptionOnInvalidBody in 309.6656131s
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @muratg

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by muratg** [comment]
@jkotalik @pakrym need to increase the timeout?

**Comment by pakrym** [comment]
No, this was fixed in https://github.com/aspnet/IISIntegration/pull/1420

**Comment by muratg** [comment]
Did that not go through the build perhaps? Check-in was around 20 hours ago and the failure 11.

**Comment by pakrym** [comment]
Failure is in master, it's not merged yet
