### ISSUE TITLE
Test failure: ReadAndWriteSynchronously

### ISSUE THREAD

**Issue by aspnet-hello** [aspnet/IISIntegration#1430]
This test [fails](http://aspnetci/viewLog.html?buildId=558536&buildTypeId=XPlat_Windows_Win2008r2_Universe) occasionally with the following error:
```
System.Net.Http.HttpRequestException : Error while copying content to a stream.
---- System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
-------- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.LoggingHandler.LogResponse(LogLevel logLevel, HttpResponseMessage response) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/LoggingHandler.cs:line 50
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.LoggingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Microsoft.AspNetCore.Server.IntegrationTesting.IIS/LoggingHandler.cs:line 29
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.SynchronousReadAndWriteTests.ReadAndWriteSynchronously() in /_/test/Common.FunctionalTests/Inprocess/SynchronousReadAndWriteTests.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
----- Inner Stack Trace -----
------- Stdout: -------
| [0.004s] TestLifetime Information: Starting test ReadAndWriteSynchronously at 2018-09-21T20:11:05
| [0.005s] FIXTURE:HttpTestSite Debug: Method: POST, RequestUri: 'http://localhost:59982/ReadAndWriteSynchronously', Version: 2.0, Content: System.Net.Http.StringContent, Headers:
|                                      {
|                                        Content-Type: text/plain; charset=utf-8
|                                      }
| [0.007s] FIXTURE:HttpTestSite Debug: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
|                                      {
|                                        Transfer-Encoding: chunked
|                                        Server: Microsoft-IIS/7.5
|                                        Date: Fri, 21 Sep 2018 20:11:04 GMT
|                                      }
| [0.117s] FIXTURE:HttpTestSite Debug: hello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello worldhello w
...
```
Other tests within that build may have failed with a similar message, but they are not listed here. Check the link above for more info.

This test failed on master.

CC @muratg

This issue was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this actually a flaky test?
  * No, this is a regular test failure, fix the test/product (TODO: Link to commit/PR)
  * Yes, proceed below...

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * Is there any logging or extra information that we could add to make this more diagnosable when it happens again?
        * Yes?
            * [ ] Add the logging (TODO: Link to PR/commit)
        * No?
            * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by muratg** [comment]
@pakrym @jkotalik

**Comment by aspnet-hello** [comment]
There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=559251&buildTypeId=Releases_22xPublic_Win2012) on 2.2:
- ReadAndWriteSynchronously


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by pakrym** [comment]
I broke something. Will take a look.

**Comment by aspnet-hello** [comment]
There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=561726&buildTypeId=XPlat_Windows_Win2008r2_Universe) on master:
- ReadAndWriteSynchronously


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by aspnet-hello** [comment]
There were 1 failures [with about the same error](http://aspnetci/viewLog.html?buildId=563014&buildTypeId=XPlat_Windows_Win7_Universe) on master:
- ReadAndWriteSynchronously


This comment was made automatically. If there is a problem contact ryanbrandenburg.

**Comment by pakrym** [comment]
This seems to be a side effect of my broken disconnect change. That was reverted around the time failures stopped (https://github.com/aspnet/IISIntegration/commit/bac0f44fa7e102cf8dc6112c7dfd9f227d56708a) . Closing.
