### ISSUE TITLE
Flaky Tests: DebugLogsAreWrittenToEventLog

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#1450]
For some reason the debug log isn't getting sent to the event log.

```
 Failed   Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.LoggingTests.DebugLogsAreWrittenToEventLog(variant: Server: IIS, TFM: netcoreapp2.2, Type: Portable, Arch: x64, ANCM: V2, Host: OutOfProcess)
  Error Message:
   No entries matched by '\[aspnetcorev2.dll\] Initializing logs for .*?Description: IIS ASP.NET Core Module V2'
  Expected: True
  Actual:   False
  Stack Trace:
     at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.EventLogHelpers.AssertSingleEntry(String regexString, IEnumerable`1 entries) in /_/test/Common.FunctionalTests/Utilities/EventLogHelpers.cs:line 69
     at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.EventLogHelpers.VerifyEventLogEvent(IISDeploymentResult deploymentResult, String expectedRegexMatchString) in /_/test/Common.FunctionalTests/Utilities/EventLogHelpers.cs:line 24
     at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.LoggingTests.DebugLogsAreWrittenToEventLog(TestVariant variant) in /_/test/Common.FunctionalTests/LogFileTests.cs:line 182
  --- End of stack trace from previous location where exception was thrown ---
  Standard Output Messages:
   | [0.001s] TestLifetime Information: Starting test DebugLogsAreWrittenToEventLog-Server: IIS, TFM: netcoreapp2.2, Type: Portable, Arch: x64, ANCM: V2, Host: OutOfProcess at 2018-09-27T19:54:06
   | [0.001s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Deploying [Variation] :: ServerType=IIS, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
   | [0.002s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\Users\appveyor\AppData\Local\Temp\1\5b1036776c024829803f575612f02f32\wwwroot
   | [0.003s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying static.txt
   | [0.003s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug: Processing C:\Users\appveyor\AppData\Local\Temp\1\5b1036776c024829803f575612f02f32
   | [0.004s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Abstractions.dll
   | [0.004s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Authentication.Core.dll
   | [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Connections.Abstractions.dll
   | [0.005s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Abstractions.dll
   | [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.dll
   | [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
   | [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.Abstractions.dll
   | [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.dll
   | [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.Extensions.dll
   | [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Http.Features.dll
   | [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.HttpOverrides.dll
   | [0.008s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.IISIntegration.dll
   | [0.009s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.IISIntegration.pdb
   | [0.009s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.IISIntegration.xml
   | [0.011s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.Kestrel.Core.dll
   | [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.Kestrel.dll
   | [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.Kestrel.Https.dll
   | [0.012s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll
   | [0.013s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll
   | [0.013s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.AspNetCore.WebUtilities.dll
   | [0.014s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.Configuration.Abstractions.dll
   | [0.014s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.Configuration.Binder.dll
   | [0.014s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.Configuration.dll
   | [0.015s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.Configuration.EnvironmentVariables.dll
   | [0.015s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.Configuration.FileExtensions.dll
   | [0.016s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.Configuration.Json.dll
   | [0.017s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.DependencyInjection.Abstractions.dll
   | [0.017s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.DependencyInjection.dll
   | [0.017s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.FileProviders.Abstractions.dll
   | [0.018s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.FileProviders.Physical.dll
   | [0.018s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.FileSystemGlobbing.dll
   | [0.018s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.Hosting.Abstractions.dll
   | [0.019s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.Logging.Abstractions.dll
   | [0.019s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.Logging.Configuration.dll
   | [0.020s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.Logging.Console.dll
   | [0.020s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.Logging.dll
   | [0.029s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.ObjectPool.dll
   | [0.030s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.Options.ConfigurationExtensions.dll
   | [0.030s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.Options.dll
   | [0.031s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Extensions.Primitives.dll
   | [0.031s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Microsoft.Net.Http.Headers.dll
   | [0.032s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying Newtonsoft.Json.dll
   | [0.033s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying OutOfProcessWebSite.deps.json
   | [0.033s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying OutOfProcessWebSite.dll
   | [0.034s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying OutOfProcessWebSite.pdb
   | [0.034s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying OutOfProcessWebSite.runtimeconfig.json
   | [0.035s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying System.IO.Pipelines.dll
   | [0.036s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying System.Runtime.CompilerServices.Unsafe.dll
   | [0.036s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying System.Text.Encodings.Web.dll
   | [0.036s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying web.config
   | [0.037s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying xunit.abstractions.dll
   | [0.037s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying xunit.assert.dll
   | [0.038s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying xunit.core.dll
   | [0.038s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Debug:   Copying xunit.execution.dotnet.dll
   | [0.078s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: W3SVC status Running
   | [0.468s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Starting pool, state: Started
   | [0.472s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Starting site, state: Started
   | [0.693s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Site has started.
   | [0.695s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Successfully finished IIS application directory setup.
   | [0.695s] HttpTestSite Debug: Method: GET, RequestUri: 'http://localhost:50721/HelloWorld', Version: 2.0, Content: <null>, Headers:
   |                              {
   |                              }
   | [1.510s] HttpTestSite Debug: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
   |                              {
   |                                Transfer-Encoding: chunked
   |                                Server: Kestrel
   |                                Date: Thu, 27 Sep 2018 19:54:07 GMT
   |                              }
   | [1.511s] HttpTestSite Debug: Hello World
   | [1.524s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Stopping site, state: Stopped
   | [1.528s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Stopping pool, state: Stopping
   | [3.028s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Site has stopped successfully.
   | [3.038s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: Host process shutting down.
   | [3.038s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [aspnetcorev2.dll] Initializing logs for 'C:\projects\iisintegration\test\IIS.FunctionalTests\bin\Release\netcoreapp2.2\x64\aspnetcorev2.dll'. Process Id: 5644.. File Version: 12.2.18270.0. Description: IIS ASP.NET Core Module V2. Commit: 5aedbccac5c0a747f4aa94467fe5379142143bb8.
   | [3.039s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [aspnetcorev2.dll] Loading request handler:  'C:\projects\iisintegration\test\IIS.FunctionalTests\bin\Release\netcoreapp2.2\x64\2.0.0\aspnetcorev2_outofprocess.dll'
   | [3.039s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [aspnetcorev2.dll] Creating handler application
   | [3.039s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [aspnetcorev2_outofprocess.dll] Initializing logs for 'C:\projects\iisintegration\test\IIS.FunctionalTests\bin\Release\netcoreapp2.2\x64\2.0.0\aspnetcorev2_outofprocess.dll'. Process Id: 5644.. File Version: 12.2.18270.0. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: 5aedbccac5c0a747f4aa94467fe5379142143bb8.
   | [3.039s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [aspnetcorev2_outofprocess.dll] Starting app_offline monitoring in application 'C:\Users\appveyor\AppData\Local\Temp\1\5b1036776c024829803f575612f02f32\'
   | [3.039s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [aspnetcorev2_outofprocess.dll] Starting file watcher thread
   | [3.039s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [aspnetcorev2_outofprocess.dll] Failed HRESULT returned: 0x80070585 at c:\projects\iisintegration\src\aspnetcoremodulev2\outofprocessrequesthandler\outprocessapplication.cpp:90 
   | [3.039s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [aspnetcorev2_outofprocess.dll] Event Log: 'Application '/LM/W3SVC/1/ROOT' started process '5808' successfully and process '5808' is listening on port '20267'.' 
   | [3.040s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: End Event Log Message.
   | [3.040s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::OnGlobalStopListening
   | [3.040s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [aspnetcorev2.dll] Stopping application '/LM/W3SVC/1/ROOT'
   | [3.040s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [aspnetcorev2_outofprocess.dll] Stopping file watcher thread
   | [3.040s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [aspnetcorev2_outofprocess.dll] Event Log: 'Sent shutdown HTTP message to process '5808' and received http status '202'.' 
   | [3.040s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: End Event Log Message.
   | [3.040s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [aspnetcorev2_outofprocess.dll] Event Log: 'Application '/LM/W3SVC/1/ROOT' with physical root 'C:\Users\appveyor\AppData\Local\Temp\1\5b1036776c024829803f575612f02f32\' shut down process with Id '5808' listening on port '20267'' 
   | [3.040s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: End Event Log Message.
   | [3.040s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::Terminate
   | [3.049s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer Information: [Time]: Total time taken for this test variation '3.047108' seconds
```

**Comment by jkotalik** [comment]
Haven't seen this failure in a while. Closing and will let RAAS reopen if there are more issues.
