### ISSUE TITLE
Flaky Test: CheckFrebDisconnect

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#1487]
```
 Failed   Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.FrebTests.CheckFrebDisconnect
2018-10-09T23:44:57.5718697Z   Error Message:
2018-10-09T23:44:57.5719409Z    The collection contained 0 matching element(s) instead of 1.
2018-10-09T23:44:57.5728543Z   Stack Trace:
2018-10-09T23:44:57.5728777Z      at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.FrebTests.AssertFrebLogs(IISDeploymentResult result, String[] data) in /_/test/Common.FunctionalTests/Inprocess/FrebTests.cs:line 111
2018-10-09T23:44:57.5731665Z      at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.FrebTests.CheckFrebDisconnect() in /_/test/Common.FunctionalTests/Inprocess/FrebTests.cs:line 86
2018-10-09T23:44:57.5732398Z   --- End of stack trace from previous location where exception was thrown ---
2018-10-09T23:44:57.5733627Z   Standard Output Messages:
2018-10-09T23:44:57.5733961Z    | [0.000s] TestLifetime Information: Starting test CheckFrebDisconnect at 2018-10-09T23:44:49
2018-10-09T23:44:57.5734237Z    | [0.003s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True

2018-10-09T23:44:57.5752100Z    | [0.040s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Attempting to start IIS Express on port: 2634
2018-10-09T23:44:57.5752261Z    | [0.042s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Saving Config to C:\Users\VssAdministrator\AppData\Local\Temp\tmp78C4.tmp
2018-10-09T23:44:57.5752517Z    | [0.043s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Executing command : C:\Program Files\IIS Express\iisexpress.exe /site:HttpTestSite /config:C:\Users\VssAdministrator\AppData\Local\Temp\tmp78C4.tmp /trace:error /systray:false
2018-10-09T23:44:57.5752872Z    | [0.043s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
2018-10-09T23:44:57.5753049Z    | [0.043s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
2018-10-09T23:44:57.5753262Z    | [0.043s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: SET ASPNETCORE_MODULE_DEBUG=console
2018-10-09T23:44:57.5753426Z    | [0.045s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress Process 7976 started
2018-10-09T23:44:57.5753629Z    | [1.808s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Starting IIS Express ...
2018-10-09T23:44:57.5753824Z    | [2.245s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Initializing the W3 Server Started CTC = 1933515 
2018-10-09T23:44:57.5754101Z    | [2.267s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: W3 Server initializing WinSock.  CTC = 1933531 
2018-10-09T23:44:57.5754281Z    | [2.267s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: W3 Server WinSock initialized.  CTC = 1933531 
2018-10-09T23:44:57.5754552Z    | [2.268s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: W3 Server ThreadPool initialized (ipm has signalled).  CTC = 1933531 
2018-10-09T23:44:57.5754753Z    | [2.339s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Initializing logs for 'D:\a\1\s\test\IISExpress.FunctionalTests\bin\Release\netcoreapp2.2\x64\aspnetcorev2.dll'. Process Id: 7976.. File Version: 12.2.18282.0. Description: IIS ASP.NET Core Module V2. Commit: .
2018-10-09T23:44:57.5755125Z    | [2.341s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Start listenerChannel http:0
2018-10-09T23:44:57.5755359Z    | [2.343s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Successfully registered URL "http://localhost:2634/" for site "HttpTestSite" application "/"
2018-10-09T23:44:57.5755546Z    | [2.344s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Registration completed for site "HttpTestSite"
2018-10-09T23:44:57.5755772Z    | [2.345s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: AppPool 'IISExpressAppPool' initialized
2018-10-09T23:44:57.5755953Z    | [2.346s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: InitComplete event signalled
2018-10-09T23:44:57.5756482Z    | [2.347s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: IIS Express is running.
2018-10-09T23:44:57.5756654Z    | [2.347s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Started iisexpress successfully. Process Id : 7976, Port: 2634
2018-10-09T23:44:57.5756877Z    | [2.350s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Application ready at URL: http://localhost:2634/
2018-10-09T23:44:57.5757037Z    | [2.355s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: IncrementMessages called
2018-10-09T23:44:57.5757299Z    | [2.355s] HttpTestSite Debug: Method: GET, RequestUri: 'http://localhost:2634/WaitingRequestCount', Version: 2.0, Content: <null>, Headers:
2018-10-09T23:44:57.5769388Z    |                              {
2018-10-09T23:44:57.5769507Z    |                              }
2018-10-09T23:44:57.5769648Z    | [2.357s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: IncrementMessages called
2018-10-09T23:44:57.5769741Z    | [2.386s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Request started: "GET" http://localhost:2634/WaitingRequestCount
2018-10-09T23:44:57.5769885Z    | [2.386s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Request started: "GET" http://localhost:2634/WaitForAbort
2018-10-09T23:44:57.5769998Z    | [2.401s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Resolving hostfxr parameters for application: 'dotnet' arguments: '.\InProcessWebSite.dll' path: 'C:\Users\VssAdministrator\AppData\Local\Temp\3c2752b920f44c008e742805e80bfed5\'
2018-10-09T23:44:57.5770174Z    | [2.401s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Known dotnet.exe location: ''
2018-10-09T23:44:57.5770268Z    | [2.401s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Process path 'dotnet.exe' is dotnet, treating application as portable
2018-10-09T23:44:57.5770411Z    | [2.401s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Resolving absolute path to dotnet.exe from 'dotnet.exe'
2018-10-09T23:44:57.5770503Z    | [2.401s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Invoking where.exe to find dotnet.exe
2018-10-09T23:44:57.5770643Z    | [2.522s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] where.exe invocation returned: 'D:\a\1\s\.dotnet\x64\dotnet.exe
2018-10-09T23:44:57.5770884Z    | [2.522s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: C:\Program Files\dotnet\dotnet.exe
2018-10-09T23:44:57.5771028Z    | [2.522s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: '
2018-10-09T23:44:57.5771162Z    | [2.522s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Current process bitness type detected as isX64=1
2018-10-09T23:44:57.5771311Z    | [2.523s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Processing entry 'D:\a\1\s\.dotnet\x64\dotnet.exe'
2018-10-09T23:44:57.5771401Z    | [2.523s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Binary type 6
2018-10-09T23:44:57.5771571Z    | [2.524s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Found dotnet.exe via where.exe invocation at 'D:\a\1\s\.dotnet\x64\dotnet.exe'
2018-10-09T23:44:57.5771672Z    | [2.524s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Resolving absolute path to hostfxr.dll from 'D:\a\1\s\.dotnet\x64\dotnet.exe'
2018-10-09T23:44:57.5771828Z    | [2.526s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] hostfxr.dll located at 'D:\a\1\s\.dotnet\x64\host\fxr\2.2.0-preview3-27001-02\hostfxr.dll'
2018-10-09T23:44:57.5771940Z    | [2.526s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Converted argument '.\InProcessWebSite.dll' to 'C:\Users\VssAdministrator\AppData\Local\Temp\3c2752b920f44c008e742805e80bfed5\.\InProcessWebSite.dll'
2018-10-09T23:44:57.5772214Z    | [2.526s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Parsed hostfxr options: dotnet location: 'D:\a\1\s\.dotnet\x64\dotnet.exe' hostfxr path: 'D:\a\1\s\.dotnet\x64\host\fxr\2.2.0-preview3-27001-02\hostfxr.dll' arguments:
2018-10-09T23:44:57.5772320Z    | [2.527s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Argument[0] = 'D:\a\1\s\.dotnet\x64\dotnet.exe'
2018-10-09T23:44:57.5772469Z    | [2.527s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Argument[1] = 'C:\Users\VssAdministrator\AppData\Local\Temp\3c2752b920f44c008e742805e80bfed5\.\InProcessWebSite.dll'
2018-10-09T23:44:57.5772579Z    | [3.097s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Loading request handler:  'C:\Users\VssAdministrator\AppData\Local\Temp\3c2752b920f44c008e742805e80bfed5\aspnetcorev2_inprocess.dll'
2018-10-09T23:44:57.5772794Z    | [3.101s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Initializing logs for 'C:\Users\VssAdministrator\AppData\Local\Temp\3c2752b920f44c008e742805e80bfed5\aspnetcorev2_inprocess.dll'. Process Id: 7976.. File Version: 12.2.18282.0. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: .
2018-10-09T23:44:57.5773098Z    | [3.101s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Creating handler application
2018-10-09T23:44:57.5773740Z    | [3.106s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Waiting for initialization
2018-10-09T23:44:57.5774174Z    | [3.107s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Starting in-process worker thread
2018-10-09T23:44:57.5774459Z    | [3.107s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Resolving hostfxr parameters for application: 'dotnet' arguments: '.\InProcessWebSite.dll' path: 'C:\Users\VssAdministrator\AppData\Local\Temp\3c2752b920f44c008e742805e80bfed5\'
2018-10-09T23:44:57.5774691Z    | [3.108s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Known dotnet.exe location: 'D:\a\1\s\.dotnet\x64\dotnet.exe'
2018-10-09T23:44:57.5774934Z    | [3.108s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Process path 'dotnet.exe' is dotnet, treating application as portable
2018-10-09T23:44:57.5775233Z    | [3.108s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Resolving absolute path to hostfxr.dll from 'D:\a\1\s\.dotnet\x64\dotnet.exe'
2018-10-09T23:44:57.5775409Z    | [3.110s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] hostfxr.dll located at 'D:\a\1\s\.dotnet\x64\host\fxr\2.2.0-preview3-27001-02\hostfxr.dll'
2018-10-09T23:44:57.5775670Z    | [3.110s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Converted argument '.\InProcessWebSite.dll' to 'C:\Users\VssAdministrator\AppData\Local\Temp\3c2752b920f44c008e742805e80bfed5\.\InProcessWebSite.dll'
2018-10-09T23:44:57.5778439Z    | [3.110s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Parsed hostfxr options: dotnet location: 'D:\a\1\s\.dotnet\x64\dotnet.exe' hostfxr path: 'D:\a\1\s\.dotnet\x64\host\fxr\2.2.0-preview3-27001-02\hostfxr.dll' arguments:
2018-10-09T23:44:57.5778877Z    | [3.110s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Argument[0] = 'D:\a\1\s\.dotnet\x64\dotnet.exe'
2018-10-09T23:44:57.5781602Z    | [3.111s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Argument[1] = 'C:\Users\VssAdministrator\AppData\Local\Temp\3c2752b920f44c008e742805e80bfed5\.\InProcessWebSite.dll'
2018-10-09T23:44:57.5785324Z    | [4.811s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Request ended: http://localhost:2634/WaitingRequestCount with HTTP status 200.0
2018-10-09T23:44:57.5785443Z    | [4.813s] HttpTestSite Debug: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
2018-10-09T23:44:57.5785599Z    |                              {
2018-10-09T23:44:57.5785664Z    |                                Transfer-Encoding: chunked
2018-10-09T23:44:57.5785767Z    |                                Server: Microsoft-IIS/10.0
2018-10-09T23:44:57.5785851Z    |                                X-SourceFiles: =?UTF-8?B?QzpcVXNlcnNcVnNzQWRtaW5pc3RyYXRvclxBcHBEYXRhXExvY2FsXFRlbXBcM2MyNzUyYjkyMGY0NGMwMDhlNzQyODA1ZTgwYmZlZDVcV2FpdGluZ1JlcXVlc3RDb3VudA==?=
2018-10-09T23:44:57.5785926Z    |                                X-Powered-By: ASP.NET
2018-10-09T23:44:57.5786293Z    |                                Date: Tue, 09 Oct 2018 23:44:53 GMT
2018-10-09T23:44:57.5786361Z    |                              }
2018-10-09T23:44:57.7806927Z    | [4.822s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Request ended: http://localhost:2634/WaitingRequestCount with HTTP status 200.0
2018-10-09T23:44:57.7807401Z    | [4.822s] HttpTestSite Debug: 1
2018-10-09T23:44:57.7807526Z    | [4.825s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Stopping IIS Express ...
2018-10-09T23:44:57.7807622Z    | [4.825s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Process Model Shutdown called
2018-10-09T23:44:57.7807831Z    | [4.826s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Request ended: http://localhost:2634/WaitForAbort with HTTP status 200.0
2018-10-09T23:44:57.7866353Z    | [4.925s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Stop listenerChannel http:0
2018-10-09T23:44:57.7866511Z    | [4.961s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] In-process callbacks set
2018-10-09T23:44:57.7866843Z    | [4.961s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Event Log: 'Application 'C:\Users\VssAdministrator\AppData\Local\Temp\3c2752b920f44c008e742805e80bfed5\' started the coreclr in-process successfully.' 
2018-10-09T23:44:57.7866952Z    | [4.961s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: End Event Log Message.
2018-10-09T23:44:57.7867103Z    | [4.961s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Starting app_offline monitoring in application 'C:\Users\VssAdministrator\AppData\Local\Temp\3c2752b920f44c008e742805e80bfed5\'
2018-10-09T23:44:57.7867241Z    | [4.961s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Starting file watcher thread
2018-10-09T23:44:57.7867349Z    | [4.961s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Hosting environment: Production
2018-10-09T23:44:57.7867694Z    | [4.961s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Content root path: C:\Users\VssAdministrator\AppData\Local\Temp\3c2752b920f44c008e742805e80bfed5
2018-10-09T23:44:57.7867789Z    | [4.961s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Application started. Press Ctrl+C to shut down.
2018-10-09T23:44:57.7867918Z    | [4.961s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[11]
2018-10-09T23:44:57.7868006Z    | [4.961s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout:       Hosting startup assembly exception
2018-10-09T23:44:57.7868156Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: System.InvalidOperationException: Startup assembly Microsoft.AspNetCore.Server.IISIntegration failed to execute. See the inner exception for more details. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Server.IISIntegration, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
2018-10-09T23:44:57.7868308Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout:    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
2018-10-09T23:44:57.7868466Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout:    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
2018-10-09T23:44:57.7868712Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout:    at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
2018-10-09T23:44:57.7868815Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout:    at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
2018-10-09T23:44:57.7868938Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout:    --- End of inner exception stack trace ---
2018-10-09T23:44:57.7869065Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
2018-10-09T23:44:57.7869177Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout:       Request starting HTTP/1.1 GET http://localhost:2634/WaitingRequestCount  
2018-10-09T23:44:57.7869295Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
2018-10-09T23:44:57.7869387Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout:       Request starting HTTP/1.1 GET http://localhost/WaitForAbort  
2018-10-09T23:44:57.7869506Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
2018-10-09T23:44:57.7869593Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout:       Request finished in 98.4927ms 200 
2018-10-09T23:44:57.7869797Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
2018-10-09T23:44:57.7869885Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout:       Request finished in 145.7671ms 0 
2018-10-09T23:44:57.7870012Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::OnGlobalStopListening
2018-10-09T23:44:57.7870105Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] Stopping application '/LM/W3SVC/1/ROOT'
2018-10-09T23:44:57.7870219Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Stopping CLR
2018-10-09T23:44:57.7870315Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Starting shutdown sequence 0
2018-10-09T23:44:57.7870444Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Application is shutting down...
2018-10-09T23:44:57.7870534Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Managed application exited with code 0
2018-10-09T23:44:57.7870649Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Clr thread wait ended: clrThreadExited: 1
2018-10-09T23:44:57.7870746Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Event Log: 'Application 'MACHINE/WEBROOT/APPHOST/HTTPTESTSITE' has shutdown.' 
2018-10-09T23:44:57.7870956Z    | [4.962s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: End Event Log Message.
2018-10-09T23:44:57.7871051Z    | [4.963s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Stopping in-process worker thread
2018-10-09T23:44:57.7871173Z    | [4.963s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2_inprocess.dll] Stopping file watcher thread
2018-10-09T23:44:57.7871263Z    | [5.125s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Waiting for all LISTENER_CHANNELS to stop
2018-10-09T23:44:57.7871382Z    | [5.326s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Waiting for all LISTENER_CHANNELS to stop
2018-10-09T23:44:57.7871469Z    | [5.527s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Waiting for all LISTENER_CHANNELS to stop
2018-10-09T23:44:57.7871600Z    | [5.728s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Waiting for all LISTENER_CHANNELS to stop
2018-10-09T23:44:57.7871685Z    | [5.928s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Waiting for all LISTENER_CHANNELS to stop
2018-10-09T23:44:57.7871830Z    | [5.965s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: UL_NATIVE_REQUEST::ReleaseAllWorkerRequests waiting for 13 requests to drain.
2018-10-09T23:44:57.7872088Z    | [5.966s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Terminating W3_SERVER object
2018-10-09T23:44:57.7872953Z    | [6.081s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [aspnetcorev2.dll] ASPNET_CORE_GLOBAL_MODULE::Terminate
2018-10-09T23:44:57.7873327Z    | [6.129s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Waiting for all LISTENER_CHANNELS to stop
2018-10-09T23:44:57.7873543Z    | [6.329s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Waiting for all LISTENER_CHANNELS to stop
2018-10-09T23:44:57.7873749Z    | [6.530s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Waiting for all LISTENER_CHANNELS to stop
2018-10-09T23:44:57.7873999Z    | [6.731s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Waiting for all LISTENER_CHANNELS to stop
2018-10-09T23:44:57.7874171Z    | [6.931s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Waiting for all LISTENER_CHANNELS to stop
2018-10-09T23:44:57.7874398Z    | [7.132s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Waiting for all LISTENER_CHANNELS to stop
2018-10-09T23:44:57.7874551Z    | [7.256s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: IIS Express stopped.
2018-10-09T23:44:57.7874737Z    | [7.409s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress Process 7976 shut down
2018-10-09T23:44:57.7874888Z    | [7.409s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Host process shutting down.
2018-10-09T23:44:57.7875077Z    | [7.409s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Deleting applicationHost.config file from C:\Users\VssAdministrator\AppData\Local\Temp\tmp78C4.tmp
2018-10-09T23:44:57.7875279Z    | [7.436s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: [Time]: Total time taken for this test variation '7.4329887' seconds
2018-10-09T23:44:57.7875552Z   
2018-10-09T23:44:57.7875669Z   
```

**Comment by jkotalik** [comment]
Done, will reopen if failures continue.
