### ISSUE TITLE
Cannot load DLL at runtime when publishing with Visual Studio 2015.

### ISSUE THREAD

**Issue by jamespedid** [aspnet/IISIntegration#308]
Hello, I'm not sure if this is the appropriate place for this, but I can't seem to find much information about an issue that I am having.

A quick description: I have three projects: a class library, an executable, and an asp.net core server rigged up to run the .NET 4.5.2 framework. (By rigged up, I mean this is created from the template provided to visual studio 2015.)

The ASP.NET core application hosts the executable (and scrapes suitable command line information in the process). The executable is throwing the error here. (It is being run using a Process.Start kind of deal).

The ASP.NET application works fine in debug mode. However, after I publish it to a .zip file and import it into IIS, I'm running into a runtime error with regards to loading an apparent nuget dependency. The error resembles the following:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
at net.openstack.Core.Providers.OpenStackIdentityProvider.<>c__DisplayClass4_0.<GetUserAccess>b__0()\r\n   at net.openstack.Core.Caching.UserAccessCache.<>c__DisplayClass2_0.<Get>b__0(String k)
at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
at net.openstack.Core.Caching.UserAccessCache.Get(String key, Func`1 refreshCallback, Boolean forceCacheRefresh)
at net.openstack.Core.Providers.OpenStackIdentityProvider.GetUserAccess(CloudIdentity identity, Boolean forceCacheRefresh)
at net.openstack.Providers.Rackspace.CloudIdentityProvider.Authenticate(CloudIdentity identity)
at Complion.Nutella.SwiftInterface.GetCloudFilesProvider() in D:\\CodeBase\\Complion.Nutella\\Complion.Nutella\\SwiftInterface.cs:line 38
at Complion.Nutella.SwiftInterface.get_CloudFilesProvider() in D:\\CodeBase\\Complion.Nutella\\Complion.Nutella\\SwiftInterface.cs:line 25
at Complion.Nutella.SwiftInterface.DownloadTemporaryFile(String containerId, String objectName, String mimeType, String fileExtension) in D:\\CodeBase\\Complion.Nutella\\Complion.Nutella\\SwiftInterface.cs:line 51
at Complion.Nutella.Runner.Program.ConvertSwiftDocument(List`1 options) in D:\\CodeBase\\Complion.Nutella\\Complion.Nutella.Runner\\Program.cs:line 73
   at Complion.Nutella.Runner.Program.Main(String[] args) in D:\\CodeBase\\Complion.Nutella\\Complion.Nutella.Runner\\Program.cs:line 28
```

The only thing that I can trace this error towards is being published; building the executable on the intended server with visual studio works fine, as well as the developer machine. Deploying to IIS in this manner seems to be leading to the problem.

If you have any direction, that would be appreciated.

**Comment by muratg** [comment]
@jamespedid did you figure this out? It looks like you can simplify your deployment a bit, I assume you already did :)

**Comment by jamespedid** [comment]
I did not and I switched to a non-core application, and that is what we went with.
