### ISSUE TITLE
Inprocess: NativeIISSample fails to start with outofprocess mode

### ISSUE THREAD

**Issue by Tratcher** [aspnet/IISIntegration#455]
_From @jhkimnew on October 20, 2017 21:54_

Try to start NativeIISSample with setting outofprocess mode and you will get this error.

C:\inetpub\wwwroot\NativeIISSample>dotnet .\NativeIISSample.dll
Application startup exception: System.InvalidOperationException: No service for type 'Microsoft.AspNetCore.Hosting.Server.IServer' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureServer()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Unhandled Exception: System.InvalidOperationException: No service for type 'Microsoft.AspNetCore.Hosting.Server.IServer' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureServer()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at NativeIISSample.Startup.Main(String[] args) in D:\GitRoot\IISIntegration\samples\NativeIISSample\Startup.cs:line 65

_Copied from original issue: aspnet/AspNetCoreModule#203_

**Comment by jkotalik** [comment]
Closing in favor of #456
