### ISSUE TITLE
HelloWorldTests,  HttpsTest,  NtlmAuthenticationTests broken on CI.

### ISSUE THREAD

**Issue by pakrym** [aspnet/IISIntegration#472]
```
System.IO.FileNotFoundException : AspNetCoreModule could not be found.
   at Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer.<StartIISExpressAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer.<DeployAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.NtlmAuthenticationTests.<NtlmAuthentication>d__3.MoveNext() in C:\b\w\33bdfc1cae7b2a38\modules\IISIntegration\test\IISIntegration.FunctionalTests\NtlmAuthentationTest.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| TestLifetime Information: Starting test NtlmAuthentication_Clr
| Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=Clr, Arch=x64, BaseUrlHint=http://localhost:5051, Publish=False
| Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: SET ASPNETCORE_ENVIRONMENT=NtlmAuthentication
| Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Executing command dotnet publish  --output "C:\b\t\buildTmp\8e4aeda8-6432-4d24-9b83-5d9b05b565ff" --framework net461 --configuration Debug --no-restore 
| Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
| Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout:   Microsoft.AspNetCore.Server.IISIntegration -> C:\b\w\33bdfc1cae7b2a38\modules\IISIntegration\src\Microsoft.AspNetCore.Server.IISIntegration\bin\Debug\netstandard2.0\Microsoft.AspNetCore.Server.IISIntegration.dll
| Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout:   TestSites -> C:\b\w\33bdfc1cae7b2a38\modules\IISIntegration\test\TestSites\bin\Debug\net461\TestSites.exe
| Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet-publish stdout:   TestSites -> C:\b\t\buildTmp\8e4aeda8-6432-4d24-9b83-5d9b05b565ff\
| Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: dotnet publish finished with exit code : 0
| Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Attempting to start IIS Express on port: 5051
| Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: Host process already exited or never started successfully.
| Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: [Time]: Total time taken for this test variation '3.0184345' seconds
| TestLifetime Information: Finished test NtlmAuthentication_Clr in 3.0195145s

```

**Comment by Tratcher** [comment]
The dll path was changed recently. @jkotalik did you get everything updated yet?

**Comment by jkotalik** [comment]
Should be fixed by https://github.com/aspnet/Hosting/pull/1258
