### ISSUE TITLE
IPv4 loopback interface: port already in use After Azure WebApp restart

### ISSUE THREAD

**Issue by Julien-Mialon** [aspnet/IISIntegration#483]
Last night our Azure web app restarted (automatically) and didn't come back online as usual. 

It failed with an IOException because it can't bind to the IPV4 address because the port is already in use. Generally we saw this error only on IPV6 address and do not stop the app working correctly but tonight, it never bound to IPV4 nor IPV6.

Below the exception in our application log file : 
```
2017-12-01 04:39:19.439 +00:00 [Debug] Hosting starting
2017-12-01 04:39:19.845 +00:00 [Fatal] Unable to start Kestrel.
System.IO.IOException: Failed to bind to address http://localhost:27151 on the IPv4 loopback interface: port already in use. ---> System.AggregateException: One or more errors occurred. ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4091 EADDRINUSE address already in use
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_getsockname(UvTcpHandle handle, SockAddr& addr, Int32& namelen)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.GetSockIPEndPoint()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListener.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
2017-12-01 04:39:34.841 +00:00 [Debug] Hosting shutdown
```

And the eventlogs in the webapp azure (via kudu) : 
```xml
<Event>
    <System>
        <Provider Name=".NET Runtime"/>
        <EventID>1026</EventID>
        <Level>1</Level>
        <Task>0</Task>
        <Keywords>Keywords</Keywords>
        <TimeCreated SystemTime="2017-12-01T04:39:32Z"/>
        <EventRecordID>3043718</EventRecordID>
        <Channel>Application</Channel>
        <Computer>RD00155D4907E5</Computer>
        <Security/>
    </System>
    <EventData>
        <Data>
Application: Alerto.Api.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_getsockname(Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle, Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.SockAddr ByRef, Int32 ByRef) at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.GetSockIPEndPoint() at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListener.CreateListenSocket() at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.
            <StartAsync>b__8_0(System.Object) Exception Info: System.AggregateException at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean) at System.Threading.Tasks.Task.Wait(Int32, System.Threading.CancellationToken) at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(Microsoft.AspNetCore.Server.Kestrel.ServerAddress) at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](Microsoft.AspNetCore.Hosting.Server.IHttpApplication`1
                <Context>) Exception Info: System.IO.IOException at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](Microsoft.AspNetCore.Hosting.Server.IHttpApplication`1
                    <Context>) at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start() at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(Microsoft.AspNetCore.Hosting.IWebHost, System.Threading.CancellationToken, System.String) at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(Microsoft.AspNetCore.Hosting.IWebHost) at Alerto.Api.Program.Main(System.String[])

                    </Data>
                </EventData>
            </Event>
            <Event>
                <System>
                    <Provider Name="IIS AspNetCore Module"/>
                    <EventID>1000</EventID>
                    <Level>1</Level>
                    <Task>0</Task>
                    <Keywords>Keywords</Keywords>
                    <TimeCreated SystemTime="2017-12-01T04:39:35Z"/>
                    <EventRecordID>3046734</EventRecordID>
                    <Channel>Application</Channel>
                    <Computer>RD00155D4907E5</Computer>
                    <Security/>
                </System>
                <EventData>
                    <Data>
Application 'MACHINE/WEBROOT/APPHOST/ALERTO-API' with physical root 'D:\home\site\wwwroot\' failed to start process with commandline 'D:\home\site\wwwroot\Alerto.Api.exe ', ErrorCode = '0x80004005 : e0434352.
</Data>
                </EventData>
            </Event>
            <Event>
                <System>
                    <Provider Name="IIS AspNetCore Module"/>
                    <EventID>1001</EventID>
                    <Level>4</Level>
                    <Task>0</Task>
                    <Keywords>Keywords</Keywords>
                    <TimeCreated SystemTime="2017-12-01T04:39:48Z"/>
                    <EventRecordID>3059531</EventRecordID>
                    <Channel>Application</Channel>
                    <Computer>RD00155D4907E5</Computer>
                    <Security/>
                </System>
                <EventData>
                    <Data>
Application 'MACHINE/WEBROOT/APPHOST/ALERTO-API' started process '5940' successfully and is listening on port '21764'.
</Data>
                </EventData>
            </Event>
            <Event>
                <System>
                    <Provider Name="IIS AspNetCore Module"/>
                    <EventID>1005</EventID>
                    <Level>2</Level>
                    <Task>0</Task>
                    <Keywords>Keywords</Keywords>
                    <TimeCreated SystemTime="2017-12-01T04:40:17Z"/>
                    <EventRecordID>166290718</EventRecordID>
                    <Channel>Application</Channel>
                    <Computer>RD00155D49392E</Computer>
                    <Security/>
                </System>
                <EventData>
                    <Data>Failed to gracefully shutdown process '10812'.</Data>
                </EventData>
            </Event>
``` 

This application is running in production for the last 10 month without any issue and no deployment has been made in the last month so a code error would seems strange. We supposed an error with IIS Integration where kestrel failed to start but IIS was started correctly.

I can provide more informations if needed.

**Comment by halter73** [comment]
It is expected that this can happen rarely during server restarts because ANCM selects a random port without first checking if it's in use.

This is usually benign though since the error only happens on server startup and ANCM should restart the process up to ten times in a row after it crashes. Is that not happening in this case?

**Comment by Julien-Mialon** [comment]
No in our case, It hasn't restarted after this error. We had to manually restart the webapp from azure portal to make it restart correctly.

**Comment by Julien-Mialon** [comment]
@halter73 After checking some others webapp, the AppService on azure have restarted multiple of our application at the same moment and 3 of them had the port already used error and did not restart correctly.

**Comment by Julien-Mialon** [comment]
@halter73 Do you have any update on this issue ?

**Comment by halter73** [comment]
@Julien-Mialo .NET Framework v4.7.1 was rolled out to Azure App Services within the last 5 days or so. Have you seen this issue at all in the last 5 days?

**Comment by shirhatti** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
