### ISSUE TITLE
azure hosting help

### ISSUE THREAD

**Issue by esargent** [aspnet/IISIntegration#64]
I got my app published to Azure but I'm getting that dreaded 502.3 Bad Gateway error. However after reading through everything I can find, which mostly relates to beta8/rc1 I think I'm having a slightly different problem where my app is starting just fine, even serving static files (apparently from stdout).
Everything I read here about this says this means you have the wrong version of the IISPlatformHandler, installed on server, but since I'm publishing to Azure is that even something I control?  Using rc2-16069 of the Microsoft.aspnet.IISPlaformHandler package. a hopefully relevant snippet of stdout below:

```
info: Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (1ms) [Parameters=[@__normalizedName_0='?'], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) [r].[Id], [r].[ConcurrencyStamp], [r].[Name], [r].[NormalizedName]
      FROM [AspNetRoles] AS [r]
      WHERE [r].[NormalizedName] = @__normalizedName_0
info: Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT COUNT(*)
      FROM [AspNetRoles] AS [a]
Hosting environment: Development
Now listening on: http://localhost:31949
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNet.Server.Kestrel[0]
      DispatchPipe.Accept
      Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -4050 ENOTSOCK socket operation on non-socket
         at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.Check(Int32 statusCode)
         at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.accept(UvStreamHandle server, UvStreamHandle client)
         at Microsoft.AspNet.Server.Kestrel.Http.ListenerSecondary.ReadStartCallback(UvStreamHandle handle, Int32 status)
fail: Microsoft.AspNet.Server.Kestrel[0]
      DispatchPipe.Accept
      Microsoft.AspNet.Server.Kestrel.Networking.UvException: Error -4050 ENOTSOCK socket operation on non-socket
         at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.Check(Int32 statusCode)
         at Microsoft.AspNet.Server.Kestrel.Networking.Libuv.accept(UvStreamHandle server, UvStreamHandle client)
         at Microsoft.AspNet.Server.Kestrel.Http.ListenerSecondary.ReadStartCallback(UvStreamHandle handle, Int32 status)
info: Microsoft.AspNet.Hosting.Internal.WebApplication[1]
      Request starting HTTP/1.1 GET http://aldehydes.azurewebsites.net/  
info: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1]
      Executing action method Revelar.Controllers.HomeController.Index with arguments () - ModelState is Valid'
info: Microsoft.AspNet.Mvc.ViewFeatures.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Home/Index.cshtml.
info: Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler[2]
      Executed action Revelar.Controllers.HomeController.Index in 0.2234ms
info: Microsoft.AspNet.Hosting.Internal.WebApplication[2]
      Request finished in 3484ms 200 text/html; charset=utf-8
info: Microsoft.AspNet.Hosting.Internal.WebApplication[1]
      Request starting HTTP/1.1 GET http://aldehydes.azurewebsites.net/css/fonts.css  
info: Microsoft.AspNet.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/css/fonts.css'. Physical path: 'D:\home\site\wwwroot\css\fonts.css'
info: Microsoft.AspNet.Hosting.Internal.WebApplication[2]
      Request finished in 47ms 200 text/css
```
I've tried a couple changes to web.config from what I've read but it is basically:

```
<configuration>
  <system.webServer>
    <handlers>
      <remove name="httpplatformhandler" />
      <add name="httpplatformhandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" />
    </handlers>
    <httpPlatform processPath="%home%\site\approot\web.cmd" arguments="" stdoutLogEnabled="true" stdoutLogFile="\\?\%home%\LogFiles\stdout.log" forwardWindowsAuthToken="false" startupTimeLimit="3600"></httpPlatform>
  </system.webServer>
</configuration>
```

**Comment by Tratcher** [comment]
>Error -4050 ENOTSOCK

@halter73, @cesarbs?

**Comment by halter73** [comment]
As a workaround, you can probably do something like:

    // ...
    using Microsoft.AspNet.Http.Features;
    using Microsoft.AspNet.Server.Kestrel;
    // ...

    public class Startup
    {
        public void Configure(IPplicationBuilder app, ...)
        {
            var ksi = app.ServerFeatures.Get<IKestrelServerInformation>();
            ksi.ThreadCount = 1;
            // ...

I'll be interested to see if that fixes things. If it does, then `Error -4050 ENOTSOCK` is likely relevant.

Everything *should* still work with a `ThreadCount > 1`. I'll have to investigate further.

**Comment by esargent** [comment]
That fixed it. Can't wait to understand more what was happening!!

**Comment by Tratcher** [comment]
This issue was moved to aspnet/KestrelHttpServer#582
