### ISSUE TITLE
SynchronousReadAndWriteTests.ReadAndWriteEchoTwice

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#687]
```
Assert.Equal() Failure
Expected: 20000
Actual:   12288
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.SynchronousReadAndWriteTests.<ReadAndWriteEchoTwice>d__5.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\IISIntegration\test\IISIntegration.FunctionalTests\Inprocess\SynchronousReadAndWriteTests.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by ryanbrandenburg** [comment]
[Example](http://aspnetci/viewLog.html?buildId=423753&tab=buildResultsDiv&buildTypeId=XPlat_Windows_Win10Universe#testNameId8842195102458810528).

**Comment by jkotalik** [comment]
From that example, I think Flush is actually doing the wrong behavior.

**Comment by ryanbrandenburg** [comment]
Future instances of this issue will show up [here](http://aspnetci/httpAuth/app/rest/builds?locator=tag:EchoTwice,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)).

**Comment by jkotalik** [comment]
Underlying issue: https://github.com/dotnet/corefx/issues/28251. Will reenable once fixed.

**Comment by muratg** [comment]
New CoreFX would bring Pavel's fix. 🤞
