### ISSUE TITLE
Flaky test: dotnet publish sometimes fails saying the dll is locked

### ISSUE THREAD

**Issue by jkotalik** [aspnet/IISIntegration#690]
```c#
System.AggregateException : One or more errors occurred. (One or more errors occurred. (dotnet publish exited with exit code : 1)) (The following constructor parameters did not have matching fixture data: IISTestSiteFixture fixture)
---- System.AggregateException : One or more errors occurred. (dotnet publish exited with exit code : 1)
-------- System.Exception : dotnet publish exited with exit code : 1
---- The following constructor parameters did not have matching fixture data: IISTestSiteFixture fixture

----- Inner Stack Trace #1 (System.AggregateException) -----
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.IISTestSiteFixture..ctor() in C:\b\w\791c468639bcb5dc\test\IISIntegration.FunctionalTests\Utilities\IISTestSiteFixture.cs:line 36
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationDeployer.DotnetPublish(String publishRoot)
   at Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer.DeployAsync()
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

**Comment by muratg** [comment]
This issue was moved to aspnet/Hosting#1357
