### ISSUE TITLE
Flaky test:  SynchronousReadAndWriteTests

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/IISIntegration#766]
# Likely Root Cause
https://github.com/aspnet/IISIntegration/commit/22a865b83237cd50bdb7b764a87c28a3ec046afa

# Test History
* Individual Test Case: http://aspnetci/project.html?projectId=AspNetEf&testNameId=-8781713674742420153&tab=testDetails
* All IISIntegration flaky tests: http://aspnetci/project.html?projectId=AspNetEf&tab=flakyTests&buildTypeId=Lite_IISIntegration
  * Many `SynchronousReadAndWriteTests` near the top when sorted by failure count

# Example
This test [fails](http://aspnetci/viewLog.html?buildId=443357&buildTypeId=XPlat_Windows_Win7_Universe) occasionally on the CI with the following error:

```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : The connection with the server was terminated abnormally
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IntegrationTesting.LoggingHandler.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.SynchronousReadAndWriteTests.<ReadAndWriteSynchronously>d__2.MoveNext() in C:\BuildAgent\work\33bdfc1cae7b2a38\modules\IISIntegration\test\IISIntegration.FunctionalTests\Inprocess\SynchronousReadAndWriteTests.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
```

Future instances of this failure can be seen [here](http://aspnetci/httpAuth/app/rest/builds?locator=tag:TerminatedAbnormally,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)).

**Comment by jkotalik** [comment]
Test seems to only be failing on Win7 (other failures were due to publishing). I have a hunch why it may be flaky on Win7.

**Comment by jkotalik** [comment]
cc @pakrym, this is probably due to your refactoring for websockets.

**Comment by pakrym** [comment]
Didn't see any failures after re-enabling test
