### ISSUE TITLE
Azure app slot swap - cancelled requests?

### ISSUE THREAD

**Issue by kanadaj** [aspnet/IISIntegration#955]
Whenever I do a swap from staging to production in our Azure App Service, I see a large number of SocketConnection exceptions. Is the swap operation cutting off pending requests aggressively rather than letting the old instance deal with them before restarting?

The errors I'm seeing are:
````
{
    "ClassName": "System.ObjectDisposedException",
    "Message": "Cannot access a disposed object.\r\nObject name: 'MemoryPoolBlock'.",
    "Source": "Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions",
    "StackTraceString": "   at System.Buffers.MemoryPoolBlock.Dispose()
                            at System.IO.Pipelines.BufferSegment.ResetMemory()
                            at System.IO.Pipelines.Pipe.CompletePipe()
                            at System.IO.Pipelines.Pipe.CompleteWriter(Exception exception)
                            at System.IO.Pipelines.Pipe.DefaultPipeWriter.Complete(Exception exception)
                            at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.d__22.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
                            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                            at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.d__20.MoveNext()"
}
```

**Comment by Tratcher** [comment]
There's a limited 5 second shutdown period for active requests to complete before they are terminated. If you turn on log timestamps you should see a log about the shutdown being started, a 5s delay, and then another log if there are still active requests.

**Comment by kanadaj** [comment]
It doesn't look like the shutdown period is respected:
First log in the batch:
![image](https://user-images.githubusercontent.com/3247357/41734523-26a1b472-757f-11e8-9032-120a44f0cd45.png)

Slow swap request in Azure:
![image](https://user-images.githubusercontent.com/3247357/41734599-568abd00-757f-11e8-90c1-a5a6d597ab28.png)

wouldn't this normally mean the shutdown period shouldn't have happened any sooner than 12:54:04?
But the first log is within 3 seconds, though I'm not sure how accurate Azure's timings are between the application's recorded times and the portal's timings. 

Almost all requests in our logs are under 1000ms, with 99 percentile under 350-400. So it doesn't feel quite right. Far too many errors in comparison.

**Comment by Tratcher** [comment]
What version of Asp.Net core are you running? There were issues with the shutdown signal in prior versions.

**Comment by halter73** [comment]
Even for non-graceful shutdown, this ODE shouldn't be logged. This will be fixed in 2.1.3. See aspnet/KestrelHttpServer#2638.

**Comment by kanadaj** [comment]
Oh I see.
