### ISSUE TITLE
Aspnet core application hosted on IIS ( on-premise). We encounters 502.5 error immediately after an iisreset for the first request. Subsequent requests work fine

### ISSUE THREAD

**Issue by nanram** [aspnet/IISIntegration#968]
version of aspnetcore.dll under c:\windows\system32\inetsrv folder : 7.1. 1972.0 
I see below in the IIS logs:

2018-06-19 12:02:18 10.40.21.85 GET /api/masterdata/authuser/site - 443 - 10.40.35.22 Mozilla/5.0+(Windows+NT+10.0;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/65.0.3325.162+Safari/537.36 https://contoso.sample.com/ 502 5 0 1875

At that time we see the below entry in the stdout log file:

crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
Unhandled Exception: System.IO.IOException: Failed to bind to address http://localhost:9473 on the IPv4 loopback interface: port already in use. ---> System.AggregateException: One or more errors occurred. ---> Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvException: Error -4091 EADDRINUSE address already in use
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.Libuv.tcp_getsockname(UvTcpHandle handle, SockAddr& addr, Int32& namelen)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Networking.UvTcpHandle.GetSockIPEndPoint()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.TcpListener.CreateListenSocket()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Listener.<StartAsync>b__8_0(Object state)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.KestrelEngine.CreateServer(ServerAddress address)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.KestrelServer.Start[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Start()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Glnl.Tts.Services.AppServices.Program.Main(String[] args) in d:\bld1\63\s\Services\src\AppServices\Glnl.Tts.Services.AppServices\Program.cs:line 28

Looking into the port number we case see that another aspnet core app  was owning this port.

C:\projects\tts\services\T_Notification>netstat -ano | findstr 9473
  TCP    127.0.0.1:9473         0.0.0.0:0              LISTENING       5024
  TCP    [::1]:9473             [::]:0                 LISTENING       5024

 

Below in the FREB:

71. NOTIFY_MODULE_START ModuleName="AspNetCoreModule", Notification="EXECUTE_REQUEST_HANDLER", fIsPostNotification="false" 12:02:17.812 
72. MODULE_SET_RESPONSE_ERROR_STATUS

Warning
ModuleName="AspNetCoreModule", Notification="EXECUTE_REQUEST_HANDLER", HttpStatus="502", HttpReason="Bad Gateway", HttpSubStatus="5", ErrorCode="The operation completed successfully.
(0x0)", ConfigExceptionInfo="" 12:02:18.609

The similar issue has been outlined in the below KB article:

https://github.com/aspnet/KestrelHttpServer/issues/2250

https://github.com/aspnet/AspNetCoreModule/issues/260

We disabled the App warmup settings (like always running, preload enabled etc)  which they had enabled, but still the issue happens.

Note:
The issue happens only for the first request after IISreset. Subsequent request works. 
Also if he hardcodes the port number for his app as part of .UseUrls, the issue never happens.   Currently its dynamic port.

**Comment by jkotalik** [comment]
Related to #643 . 

Thanks for the detailed report. A few things I would recommend.
- Update the version of the ANCM on your machine. You can do this installing the latest windows hosting bundle corresponding to your dotnet installation. See: https://www.microsoft.com/net/download/windows
- If this repros again, check if the app that was running on port (in your repro 9473) is the same app that you wanted to start. 

Questions
- Is this reproing consistently after IISReset? Does it repro with AppPool shutdown or site shutdown?
- Can you see if the original aspnetcore application is shutdown after IISReset?

**Comment by aspnet-hello** [comment]
We periodically close 'discussion' issues that have not been updated in a long period of time.

We apologize if this causes any inconvenience. We ask that if you are still encountering an issue, please log a new issue with updated information and we will investigate.
